### ISSUE TITLE
Change the custom modal to native alert

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#1]
Change the custom modal to the native iOS alert. https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/

![image](https://user-images.githubusercontent.com/8411406/162654069-cef9328c-6baa-49fc-a020-4e12e1f23664.png)

## To replicate
```bash
cd ~/app
yarn install
yarn ios
```

## Acceptance criteria
- Given a user
- When they scan a QR code
- Then they see the iOS alert
- And the title says
- And they have an OK and Cancel button

**Comment by Mitchell139** [comment]
https://github.com/dltxio/idem-mobile/issues/60#issuecomment-1144477512

**Comment by JasminFarhi** [comment]
TESTING NOTES 

Please use URL - https://www.qrcode-monkey.com/ (To create QR code) 
To create the QR code 
- Run expo
- Get the URL in expo exp://10.5.20.28:19000
- insert it into this link (HERE/--/request-claims?callback=https://testapi.getpaidinbitcoin.com.au/user/idem&nonce=123&claims=FullNameCredential)
- Then go to https://www.qrcode-monkey.com/
- Create the QR code and scan it with your phone 
- you should see the alert then pop up for testing
<img width="326" alt="Screen Shot 2022-06-03 at 10 30 30 am" src="https://user-images.githubusercontent.com/83386965/171761885-c1da6bdc-fd18-498c-b5ea-fc771f63af80.png">
