### ISSUE TITLE
As a non PGP user, I want the app to create a PGP key, so that I can verify my email

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#10]
## AC1

- Given I don't already have a PGP
- And I have an email and name claim
- When the user selects "Generate new PGP Key"
- Then a new PGP private key is created, public key is generated and they are saved on my device
- And I'm show an alert with the private key password

## AC2
- Given I don't already have a PGP
- And I don't have an email and name claim
- When the user selects the PGP page
- Then the "Generate PGP Key" button is greyed out
- And I'm show an alert with the error "Must have a name and email claim"

Seems like a good lib https://www.npmjs.com/package/react-native-fast-openpgp
API: https://openbase.com/js/react-native-pgp/documentation

**Comment by bitcoinbrisbane** [comment]
Lets use the native alert modal

![](https://miro.medium.com/max/562/1*iieyy72JIiUkViGrxo9kmQ.png)

**Comment by TomDodson** [comment]
Has this already been completed?

**Comment by TomDodson** [comment]
Pending expo eject issue

**Comment by C00p3rb123** [comment]
After I have created my PGP key pair and I am on the PGP key import page, I cannot see my public key.

https://user-images.githubusercontent.com/48899363/177674042-03940f30-bc2b-45c5-9303-0ecf895ca96d.MP4

**Comment by C00p3rb123** [comment]
Testing Steps
1. Create full name and email claims
2. Click import your pgp/gpg key pair
3. Touch generate new pgp key - (Success message or error message pops up)
4. Go back to claims page and repeat step 2
5. Public key should appear somewhere?

**Comment by bitcoinbrisbane** [comment]
> After I have created my PGP key pair and I am on the PGP key import page, I cannot see my public key.
> 

Good catch!  Should change the UX to pub key if one exists.  Feel free to update the AC

**Comment by C00p3rb123** [comment]
> > After I have created my PGP key pair and I am on the PGP key import page, I cannot see my public key.
> 
> Good catch! Should change the UX to pub key if one exists.

sounds good!

**Comment by C00p3rb123** [comment]
If it's not too much effort, I think there should be an error message letting people know they need to have both full name and email claims if they try to generate one without them.

**Comment by xiangzhe0812** [comment]
https://proxy.idem.com.au/swagger/
there is end point for sending signup notification.

**Comment by JasminFarhi** [comment]
Create a button that allows the user to compy their public key.

**Comment by bitcoinbrisbane** [comment]
> If it's not too much effort, I think there should be an error message letting people know they need to have both full name and email claims if they try to generate one without them.

Ive updated the AC to include this

**Comment by pondpiu** [comment]
My understanding is that name claim is required. I've add that to the AC.

**Comment by C00p3rb123** [comment]
@Mitchell139 to determine the purpose/functionality of the textbox as this ticket conflicts with #11 requirements

**Comment by C00p3rb123** [comment]
If an email or full name claim aren't present there should be an error message alerting the user to fill out those claims

**Comment by Mitchell139** [comment]
No alert is shown if the user doesn't have their name or email claim completed
