### ISSUE TITLE
As an exchange that uses IDEM, I want an IDEM user to receive a push notification, so they can register and verify without scanning a QR code

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#100]
Instead of users having to scan a QR code, an integrated website can send a push notification for user to verify

- Given I am on GPIB and I have verified all IDEM claims in the IDEM app
- When I enter my IDEM email on registration and click "Register with IDEM"
- Then an alert is shown on my IDEM app with the text "Would you like to use IDEM to register and verify with GPIB?"
- When I click notification
- Then it takes me to the vender detail screen so I can signup from there.

On GPIB https://github.com/dltxio/v2.getpaidinbitcoin.com.au/pull/145
![image](https://user-images.githubusercontent.com/8411406/175846299-3401dc69-c84b-4930-a749-e881b46ddc3b.png)

https://docs.expo.dev/push-notifications/overview/
https://expo.dev/notifications

https://www.youtube.com/watch?v=7TGQiI4guNE

**Comment by jrocca82** [comment]
@bitcoinbrisbane I think this is something that needs to come from GPIB. GPIB needs to recognize the email address and send to push notification, and then maybe navigate to idem from there and allow user to sign up in idem instead, or maybe fetch data from proxy if we are implementing that in a way that allows us to fetch data stored in idem

**Comment by xiangzhe0812** [comment]
For testing:
1. add all of the claims via IDEM,
2. verify claims vis IDEM.
3. via postmain "POST": https:proxy.idem.com.au/user/notification/[put message here]
    or 
    curl --location -g --request POST 'https:proxy.idem.com.au/user/notification/[put message here]' \
     --data-raw ''

**Comment by Mitchell139** [comment]
POST request not working
![image](https://user-images.githubusercontent.com/50130291/174723876-d707dca1-bc70-4abd-a643-a67b2d949d6c.png)

**Comment by C00p3rb123** [comment]
Currently blocked by issues in #106 
Unable to save DOB

**Comment by Mitchell139** [comment]
Testing blocked by: https://github.com/dltxio/idem-mobile/issues/106#issuecomment-1163830399

**Comment by C00p3rb123** [comment]
push tokens are not unique - because of this I receive multiple notifications

**Comment by C00p3rb123** [comment]
Given I am on GPIB and I have verified my IDEM email in the IDEM app, 
When I enter my IDEM email on registration I can not see an option to register with GPIB on both portal and test addresses 

Could you please include the link for GPIB so we know which one to use for testing/demo?

**Comment by JasminFarhi** [comment]
Testing notes 
![Screen Shot 2022-07-20 at 2 16 50 pm](https://user-images.githubusercontent.com/83386965/180099713-66aab637-b397-4f6f-8ea5-56d9d3abf206.png)
- Scan QR code and get a notification from idem, Once you press the notification it should take you to GPIB screen on 3rd parties page :)

**Comment by bitcoinbrisbane** [comment]
@C00p3rb123 https://testv2.getpaidinbitcoin.com.au/register

**Comment by C00p3rb123** [comment]
QR Code working however,

Given I am on GPIB and I have verified my IDEM email in the IDEM app, when I enter my IDEM email on registration and click "Join with IDEM" I receive an error.

UI not clear upon first viewing. Expected outcome - There should be a distinction between the QR code and email registration. For example an "OR" between the two. 

<img width="459" alt="image" src="https://user-images.githubusercontent.com/48899363/180129107-a88c133c-f6d6-4130-913b-563434f9b774.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/48899363/180129582-fed136f5-b1b3-4ac9-b7ff-69dfd766c52f.png">

**Comment by C00p3rb123** [comment]
Blocked by #292 - unable to verify all claims

**Comment by Mitchell139** [comment]
Same as https://github.com/dltxio/idem-mobile/issues/100#issuecomment-1191023105

**Comment by Mitchell139** [comment]
Idem notification doesn't contain the option to select Yes (or no). Instead, clicking on it takes the user to the GPIB page in the venders tab without signing them up

**Comment by xiangzhe0812** [comment]
@Mitchell139 Yes, we did showcase and talked about it and Lucas agree take to vender detail screen and signup, the only thing we need to do is update the ticket.

**Comment by C00p3rb123** [comment]
Blocked by #317

**Comment by C00p3rb123** [comment]
Blocked by error in #245

**Comment by C00p3rb123** [comment]
Given I am on GPIB and verified all IDEM claims in the IDEM app, when I enter my IDEM email on registration and click "Join with IDEM" I receive an error saying Name or service not known

<img width="552" alt="image" src="https://user-images.githubusercontent.com/48899363/181680784-8abd45e7-ea19-4f30-a8af-d18c62e8838f.png">
