### ISSUE TITLE
SPIKE: Investigate ejecting from expo

### ISSUE THREAD

**Issue by amagon270** [dltxio/idem-mobile#107]

**Comment by amagon270** [comment]
After ejecting to continue development everyone will need to manually install a app build on their testing device which will need to be updated every time a change to the native code is made.

**Comment by bitcoinbrisbane** [comment]
> After ejecting to continue development everyone will need to manually install a app build on their testing device which will need to be updated every time a change to the native code is made.

Thats fine.  We will use a few c++ libs for the PGP and ETH signing.
