### ISSUE TITLE
As an existing PGP user, I want to import my PGP private key into the app, so that I can verify my email address

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#11]
Users can add their PGP private key to the app by selecting it off their file system.

- Given I have a PGP private key file on my device
- When I select "Import my Private Key from my Device"
- Then I can select an .asc or .key file from my device
- Then my private key is input into the GPG/PGP text box and is automatically imported (same as if the user had pasted their key into the text box and pressed "Import my private key")
- Then I receive a verification email

Dev notes:
Once file is selected save it to IDEM apps local storage

**Comment by bitcoinbrisbane** [comment]
Error:

```
null is not an object (evaluating 'FastOpenPGPNativeModules.call')
```

**Comment by TomDodson** [comment]
Has this already been completed?

**Comment by C00p3rb123** [comment]
Unable to import .asc files and .key files from my IOS device. 
![image](https://user-images.githubusercontent.com/48899363/178903729-4582dec0-0d81-46b3-83a0-255ba7975365.png)

**Comment by pondpiu** [comment]
IANA standard for media type
https://www.iana.org/assignments/media-types/media-types.xhtml
![image](https://user-images.githubusercontent.com/10498040/178923318-4e21569a-1099-4fa5-b413-9e1ce574e43c.png)

This file picker config works on android but not on ios 
Might need to allow all file type and check file type in IDEM app instead

**Comment by C00p3rb123** [comment]
"Then my private key is input into the GPG/PGP text box and is automatically imported (same as if the user had pasted their key into the text box and pressed "Import my private key")"

I can not see the private key in the text box.  Instead, I am given a public key. (which is different to public key that was generated for this private key). 

![image](https://user-images.githubusercontent.com/48899363/179144599-03061f6f-ec03-4c40-bb88-d30b3ad861c4.png)
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/48899363/179145065-2ea90f27-333a-412e-9abf-4ed505e6a0b8.png">

**Comment by C00p3rb123** [comment]
In blocked because the changing of the textbox functionality could affect #10

**Comment by C00p3rb123** [comment]
back to testing because of this https://github.com/dltxio/idem-mobile/issues/11#issuecomment-1185139490

**Comment by C00p3rb123** [comment]
Waiting for issue regarding the standard of PGP keys to be clarified

**Comment by C00p3rb123** [comment]
Blocked due to #340

**Comment by JasminFarhi** [comment]
Unable to upload an ASC file to my I-phone. Unable to upload my private key block.

**Comment by JasminFarhi** [comment]
I don't receive an email once I import my Private Key from the device.

**Comment by Mitchell139** [comment]
Seems to import key successfully but I don't receive the verification email

**Comment by pondpiu** [comment]
New version of [react-native-fast-openpgp](https://www.npmjs.com/package/react-native-fast-openpgp) has been release with the fix from the auther. Let's see if import works now
