### ISSUE TITLE
Document Type Selection Missing

### ISSUE THREAD

**Issue by C00p3rb123** [dltxio/idem-mobile#114]
When on the documents page, and trying to make a document selection, the option for either a drivers licence or passport is not available.

![file](https://user-images.githubusercontent.com/48899363/172967541-7c7c7ed2-c93d-4c88-a01d-6f1b24609ec1.jpg)

**Comment by JasminFarhi** [comment]
The document type selector seems to be behind the photo select buttons
https://user-images.githubusercontent.com/83386965/173272538-7b3c7ec9-54eb-4d87-aa9b-80ed0385b7e5.MP4

**Comment by jrocca82** [comment]
Fixed, but Jazz going to test iphone and make PR tomorrow :)
