### ISSUE TITLE
As IDEM I want to deploy the API proxy so it can be used

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#119]
- Set up DO app for the API proxy
- When merge to main, GH action to deploy to server
https://github.com/dltxio/proxy.idem.com.au

**Comment by xcjlo985** [comment]
Note - won't be a DO droplet. Will be a DO app

**Comment by xcjlo985** [comment]
Test steps:
* Verify endpoint works - https://proxy.idem.com.au/accounts (sample endpoint that comes with the nest template)

**Comment by TomDodson** [comment]
@xcjlo985 update ticket to be app instead of droplet
