### ISSUE TITLE
SPIKE Push notification service for signing up for GPIB

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#120]
What do we use to send push notifications and how are these triggered? 

https://docs.expo.dev/push-notifications/overview/ 
https://expo.dev/notifications 
https://docs.expo.dev/push-notifications/sending-notifications/

Push notifications working, but tbd how to target individual users and integrate with GPIB.

Sample push notification on branch 120

2 HOUR ALLOCATED

**Comment by jrocca82** [comment]
Jo (Time spent-- 20 minutes):
Got expo notifications working from their API
Still unknown: Targeting individual IDEM users, integration with GPIB

![Screenshot_20220613-164424_Expo Go](https://user-images.githubusercontent.com/89630724/173295587-f4b46349-f4d5-445e-a6ed-f8e91d66ab4b.jpg)
![Screenshot_20220613-164431_Expo Go](https://user-images.githubusercontent.com/89630724/173295597-304ca23a-a67b-4d27-a97a-9adce2db6754.jpg)
![Screenshot_20220613-164436_Expo Go](https://user-images.githubusercontent.com/89630724/173295600-2c3c81f1-8e6a-4ba8-a0f3-4f28dd7fd0ef.jpg)
![Screenshot_20220613-164500_Expo Go](https://user-images.githubusercontent.com/89630724/173295603-5f8448a5-5124-4d37-a81b-71b208e05244.jpg)

**Comment by xiangzhe0812** [comment]
Update on push notification SPIKE.
1. Need user's permission to send them push notifications
2.After user agree, we need to get user's ExpoPushToken and store in somewhere ( maybe proxy back end)
3.Then we can loop user's ExpoPushToken to send message VIA expo push API or can use expo-server-sdk to do it.
