### ISSUE TITLE
As a new user, I want the app to generate a mnemonic seed, so that I can sign my claims

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#13]
Use the native alert box.

- As a new user,
- When I use the app for the first time,
- Then Im given a 12 word seed

- Create a 12 word seed based on BIP39
- Save to local file system
- There will be other tickets to encrypt with password

https://www.blockplate.com/blogs/blockplate/list-of-bip39-wallets-mnemonic-seed

![image](https://user-images.githubusercontent.com/8411406/171316395-b1e286b0-ae38-4f60-a99d-7944d9983d68.png)

**Comment by jrocca82** [comment]
Mnemonic displayed in console when first navigating to Home screen:
![Screenshot 2022-05-30 121027](https://user-images.githubusercontent.com/89630724/170905275-d1661700-029c-41f0-bee5-6ed9cfa4df30.jpg)

**Comment by jrocca82** [comment]
Need to change to alert, but will do on https://github.com/dltxio/idem-mobile/issues/50 instead

**Comment by Mitchell139** [comment]
Doesn't seem to save mnemonic after generating it. If I generate a new mnemonic, close the app and then open it again, I am prompted to generate a new mnemonic. For comparison if I create a claim and follow the same steps, the claim is still shown.  https://user-images.githubusercontent.com/50130291/171355620-52a480e7-bef0-4a9a-8818-4e933d0de4e4.mp4

**Comment by amagon270** [comment]
Testing steps.
Android - Clear Expo user storage 
IOS - Uninstall and reinstall expo
Launching the app now will ask user to create mnemonic
Click cancel
Reload the app
The prompt to create mnemonic will appear again
click ok
A loading modal will appear
A alert showing the mnemonic will appear
click ok
reload the app
the prompt will no longer appear
