### ISSUE TITLE
As IDEM I only want users to only associate documents with certain claims so they cannot associate irrelevant claims

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#142]
- Given I am on the claims page
- When I add a claim and attach a document
- Then I am only able to attached documents to claims that match the readme
https://github.com/dltxio/idem-mobile#table-of-documents 

Note: Claims that do not need supporting documentation e.g. taxnumber. Will not show available documents to be added to the claim.

**Comment by TomDodson** [comment]
Updating the readme first before adding acceptance criteria

**Comment by TomDodson** [comment]
Pending readme review

**Comment by amagon270** [comment]
This is already done according to the acceptance criteria.

**Comment by TomDodson** [comment]
https://github.com/dltxio/idem-mobile/issues/71#issuecomment-1175659965
