### ISSUE TITLE
As IDEM, I want to create a SHA256 hash of my document, so that I can use it as part of the VC payload

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#15]
When a user selects their document, create a SHA256 hash of the document that is displayed below the image of the file.

- Given a user
- When the upload a document
- Then the document hash is saved

**Comment by JasminFarhi** [comment]
Please change from 265 to 256
![Image from iOS (104)](https://user-images.githubusercontent.com/83386965/170919627-2b1ea754-ecf9-4f9d-bce7-486d139eff83.png)
