### ISSUE TITLE
As a business I want to convert idem.com.au to the standard DLTx stack so it can be styled according to the provided designs  

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#150]
Convert to HTML to React

Deploy to DO app
- PROD https://www.idem.com.au/

Set up CI/CD

**Comment by JasminFarhi** [comment]
Testing notes 
- Used react-template for setting up the react side and cd/ci 
- For the DO stuff it was set up in here 
https://cloud.digitalocean.com/apps/21bf35da-d7d9-4c62-86ff-ec6da21f7879/overview
