### ISSUE TITLE
Showcase bugs

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#159]
- Vendor list (Missing a space). Add space between.
<img src="https://user-images.githubusercontent.com/91101134/175209247-56693a74-d261-458c-9a6a-29412ae9b6b0.png" width=25% height=25%>

- Change wording to "Supported exchanges" everywhere.
<img src="https://user-images.githubusercontent.com/91101134/175209217-32ffd57c-a2b9-44ad-aa8d-8e05a3e002cd.png" width=25% height=25%>

- Change styling for all supported exchanges to their brand colours and logos 
<img src="https://user-images.githubusercontent.com/91101134/175209317-f0fcd6f8-e5f9-4813-9e81-d9f5b19901de.png" width=25% height=25%>

- Change dialog box to say: Password is incorrect not Username or password is incorrect
<img src="https://user-images.githubusercontent.com/91101134/175209557-4ad64923-1847-48e9-9c08-ba4be986fed9.png" width=25% height=25%>

**Comment by Mitchell139** [comment]
Missing vendor list ![Screenshot_20220624-144129_Expo Go.jpg](https://user-images.githubusercontent.com/50130291/175464614-de468a3f-3b2e-45cf-8755-982720ffcb00.jpg)



Logo is cut off ![Screenshot_20220624-144339_Expo Go.jpg](https://user-images.githubusercontent.com/50130291/175464664-558deac4-6a5f-4208-9b19-d7748c0a17fc.jpg)

**Comment by C00p3rb123** [comment]
When I click on supported exchanges I receive this error and it stops the app from working.

https://user-images.githubusercontent.com/48899363/175838222-225e2618-4e08-4700-a766-f28f58c4fe29.MP4
