### ISSUE TITLE
App crashes if you try to sign up to Coinstash with an email that's already signed up

### ISSUE THREAD

**Issue by Mitchell139** [dltxio/idem-mobile#164]
https://user-images.githubusercontent.com/50130291/175461878-d466ed0b-b4b6-46c9-b085-492ae2181d44.mov

**Comment by pondpiu** [comment]
i found that this is case,  coinstash api return error code 400 and make axios throw axios error in different shape than the current catch code
![image](https://user-images.githubusercontent.com/10498040/176339758-6df4ad4d-7219-4d49-a77c-fc7a98fea15a.png)

axios error should be handle differently following error type as seen in the doc https://axios-http.com/docs/handling_errors

i will try open PR to fix just this case first, but ultimately i think we should extract handle axios error function out into axios-util or some sort

**Comment by pondpiu** [comment]
Turn out the error return is GraphQL error, need to handle that as well
