### ISSUE TITLE
Unable to attach documents to claims

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#165]
When the switch is selected cannot select from documents/document menu does not appear

Should not be able to manage documents from the attach screen.

**Comment by pondpiu** [comment]
I would like to work on this issue,
my proposed changed is to make `FileList.tsx` onDeleteFile be optional

**Comment by C00p3rb123** [comment]
Documents can be selected, however they are not saved 

https://user-images.githubusercontent.com/48899363/177063581-85b9288a-9696-4ca9-9f1d-1df3fddb1349.mp4

**Comment by JasminFarhi** [comment]
Criteria do not mention saving and going back to see the document saved. This may be out of scope, and may be required in another ticket later on :)
