### ISSUE TITLE
Change "import your pgp key" to the pgp fingerprint once user has imported pgp key

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#168]
pending expo eject

- Given a PGP user,
- When I setup my PGP key
- Then I see last 8 characters of my PGP Finger print on my profile page

Property on the PGP type added here https://github.com/dltxio/idem-mobile/blob/IDEM-10/app/src/types/wallet.ts#L9

* See getFingerPrint method at https://docs.openpgpjs.org/Key.html

**Comment by bitcoinbrisbane** [comment]
> pending expo eject

expo ejected!

**Comment by bitcoinbrisbane** [comment]
Will be fixed with #9

**Comment by xiangzhe0812** [comment]
OpenPGP.convertPrivateKeyToPublicKey(privateKey) not working well, only can got half of the public key, disabled the import button for now and reported on library github.
![Screen Shot 2022-07-06 at 11 45 38 am](https://user-images.githubusercontent.com/1115763/177450962-203ccd71-5458-441d-9fe2-44cd3536c1af.png)
y

**Comment by bitcoinbrisbane** [comment]
Seems like this got merged already

**Comment by bitcoinbrisbane** [comment]
Getting an undefined 
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/8411406/181143072-8e419057-592e-4267-b9f2-73f27d9e278c.png">

**Comment by JasminFarhi** [comment]
Generate new PGP disabled still even after required information is added 
![Image from iOS (10)](https://user-images.githubusercontent.com/83386965/182521892-68c9a512-0d90-4703-a14d-c5e121252c72.png)
![Image from iOS (11)](https://user-images.githubusercontent.com/83386965/182521909-21716581-f046-4226-8879-5fc4f65c3e61.png)
![Image from iOS (12)](https://user-images.githubusercontent.com/83386965/182521915-7b021324-cb6a-44f4-97e4-968a81122c80.png)

**Comment by JasminFarhi** [comment]
Does not show fingerprint it I "import my private key" 
does not show fingerprint if I "Generate new PGP key"

**Comment by C00p3rb123** [comment]
It only works after a claim is made/ saved again. Doesn't work initially after setting up pgp key

**Comment by Mitchell139** [comment]
Doesn't generate correct fingerprint

**Comment by Mitchell139** [comment]
All caps and remove spaces. Should look like 1F8D106A

**Comment by C00p3rb123** [comment]
Still experiencing the same problem as Mitch's comments
