### ISSUE TITLE
As a user, I want to remove a previously added document, so that my documents are current and correct

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#18]
On the document list view, allow users to delete an app by swipping left.

- Given I am on the document view,
- When I swipe the document left
- Then red is shown gradually
- Then the document is deleted

**Comment by JasminFarhi** [comment]
At the moment the mechanics for deleting a document are too flexible. I can swipe either way to delete. I think we need to choose which way it goes left or right not both. Cause it gets stuck if I swipe too far right or left. 
![Image from iOS (99)](https://user-images.githubusercontent.com/83386965/170901704-a3c211ed-f2ca-4d9d-af72-6d8690ad8495.png
![Image from iOS (100)](https://user-images.githubusercontent.com/83386965/170902594-a30f164f-7c85-4981-9368-5f0c13bb1d90.png)
)
