### ISSUE TITLE
As a user I want to send push notifications from the proxy so they can be on boarded without a QR code

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#181]
- Given I have filled out all claims and verified them
- When I signup to GPIB with my IDEM verified email address
- Then I will receive a notification on my mobile device that says "Would you like to use IDEM to signup for GPIB"

**Comment by bitcoinbrisbane** [comment]
@xiangzhe0812 ill try wire up the GPIB part

**Comment by C00p3rb123** [comment]
Testing/Demo Steps:
1. Make an email claim in IDEM
2. Generate PGP using https://www.attogtech.com/pgp-key-generator with your email and name
3. Copy and paste or import the public key and click publish pgp public key
4. Go to email and verify
5. Click in verify email in IDEM
6. If email is verified in IDEM Sign up to GPIB here: https://testv2.getpaidinbitcoin.com.au/ 
7. Check to see if notification appears on phone.

**Comment by C00p3rb123** [comment]
I followed these steps and I did not receive a notification on my phone.

**Comment by bitcoinbrisbane** [comment]
@JasminFarhi to finish the FE for GPIB

**Comment by C00p3rb123** [comment]
Receiving error when I sign up with IDEM
![image](https://user-images.githubusercontent.com/48899363/180158092-fdaa4c93-e005-493e-903a-19dabbe81e7c.png)

**Comment by C00p3rb123** [comment]
Blocked by #292 - unable to verify all claims

**Comment by Mitchell139** [comment]
Still getting 400 error when entering email
![image](https://user-images.githubusercontent.com/50130291/181156686-518f4cf5-85ef-45a6-a182-71c254584447.png)

**Comment by JasminFarhi** [comment]
![Image from iOS (5)](https://user-images.githubusercontent.com/83386965/181156940-edf5f816-6ab5-4beb-b219-cf54140541c2.png)

**Comment by xiangzhe0812** [comment]
@Mitchell139 @JasminFarhi Pls check database that is the expo push notification token already been used for other user.

**Comment by xiangzhe0812** [comment]
pls delete exciting one and then verify your claims

**Comment by Mitchell139** [comment]
Email input is case sensitive.

Email claim in Idem: Jas@jas.com

Then in GPIB:
jas@jas.com (didn't work)
Jas@jas.com (did work)
