### ISSUE TITLE
User is able to make an 18+ true claim with a DOB claim that is younger than 18 years old 

### ISSUE THREAD

**Issue by C00p3rb123** [dltxio/idem-mobile#186]
![image](https://user-images.githubusercontent.com/48899363/175875634-5ac9c64b-7de3-4a54-94e5-b7059ac810ac.png)

**Comment by bitcoinbrisbane** [comment]
If we verify the user, then we should "lock" DOB, YOB claims from being edited.

**Comment by C00p3rb123** [comment]
> If we verify the user, then we should "lock" DOB, YOB claims from being edited.

@bitcoinbrisbane agreed, however this ticket's primary problem is with the 18+ claim and not whether DOB can be changed. A user is able to make an 18+ true claim if their DOB claim is younger than 18

**Comment by bitcoinbrisbane** [comment]
Closing this ticket.  Anyone can make any claim, its just not verified until it is.
