### ISSUE TITLE
As a business I want to move the "verify" button from the profile page to each individual supported exchange page so claims are verified per supported exchange

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#192]
- Given I am on a supported exchange page on the IDEM app and I have signed up for that exchange
- When I click the verify button
- Then I receive an alert "You have been verified"

**Comment by bitcoinbrisbane** [comment]
> Also, disable the button if the user has not signed up yet

You might not be able to get that information
