### ISSUE TITLE
As GPIB, I want new IDEM signups to come via the IDEM proxy, so that I don’t get spam accounts

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#193]
## Context

- Change the sites.json to include proxy = true
- On the app if proxy is set to true, concat their callback URL to the proxy, such as : `https://proxy.idem.com.au/users/signup?callback=https://portal.getpaidinbitcoin.com.au/register`
- Add an end point to the proxy as `/user/signup` (maybe basic auth from the IDEM app)

## User Story
- As the GPIB owner,
- I want new IDEM signups to come via the IDEM proxy,
- So that I don’t get spam accounts

## AC
- Given
- When
- Then

**Comment by Mitchell139** [comment]
Doesn't work https://user-images.githubusercontent.com/50130291/177693990-ea8215f3-276e-46cd-866c-52bb752c3af4.mp4

**Comment by C00p3rb123** [comment]
Request table is being updated when a user signs up to GPIB through IDEM

**Comment by Mitchell139** [comment]
Used the proxy to sign up even though useproxy=false in sites.json
![image](https://user-images.githubusercontent.com/50130291/178898547-86b70866-cbce-4792-b77a-3d1f9bbd886f.png)

![image](https://user-images.githubusercontent.com/50130291/178898454-6fa727a4-0bfb-4a15-9f81-6eeb4e1a9a6d.png)
