### ISSUE TITLE
Fix android development build

### ISSUE THREAD

**Issue by amagon270** [dltxio/idem-mobile#200]

**Comment by Mitchell139** [comment]
Crashes shortly after scanning expo QR code

`PS C:\Users\Mitchell\idem-mobile\app> yarn start
yarn run v1.22.5
$ expo start --dev-client
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (5.4.12).                │
│   You are currently using expo-cli 5.4.6                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
Starting project at C:\Users\Mitchell\idem-mobile\app
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
Starting Metro Bundler
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ ██▀ ▄▄▄██ █▄██▄████ ▄▄▄▄▄ █
█ █   █ █▀███▄▀▀▄█▀ ▄█ █ ▀█ █   █ █
█ █▄▄▄█ █▄▄█▄  ▀██▄█▄ █▀▄▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█ █ █▄▀ █▄█ █ █▄█▄▄▄▄▄▄▄█
█▄ ▀▀█▄▄▄▀ █ ▀▄█▄█ ▀▀▄█  ▄███  ▀███
██▄▀▄▄█▄ █▀▄█ █  ██ ▀ ▄ ██  ▀ ▀ ▄▀█
█▀▄█▀  ▄▄▄ █ ▀▀▄ ███▀█▀█ ▄█ ▄█ ██▀█
█▄▀█▄█▄▄▄▄█▀█ ▄ ▄▄█▀▀▄█ ▀▄ ▀▄▄▀ ▀▀█
█ ▄  ██▄▄▄█▀ ▀▄▀ █▄█ ██ ▀█ ▀█▄ ▀▄ █
████▀▄█▄█▄ ▀▄▀█▄  ▄▀▄ ▄█▄█▄█▀   ▀ █
█▀█▄▄▄ ▄▄▄ ▀█▄▄█▄█▄█▀▄▀▀▀▄ █  ▄█▄▄█
█ █▄█▄ ▄ ▄ ▄▀▀██ ██ ▀▀▄ █▄██▀██  ▀█
█▄▄█▄█▄▄▄ ▄▀ ▀▀▄ ██ ▀ ██▄ ▄▄▄  █▄ █
█ ▄▄▄▄▄ █ ▀ ██▄ ▄▄███▄██  █▄█ ▀▀ ██
█ █   █ ██▄▄▀ ▄▀ █▄▄▀▀▀▄▀  ▄▄ ███▄█
█ █▄▄▄█ █▀ ▄▄▀█ ▄██▄▄█▄███ ▀█▄▀ █▄█
█▄▄▄▄▄▄▄█▄▄█▄█▄█▄███▄██▄█▄▄▄████▄██

› Metro waiting on com.dltx.idem://expo-development-client/?url=http%3A%2F%2F10.5.20.39%3A8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Press a │ open Android
› Press w │ open web

› Press r │ reload app
› Press m │ toggle menu
› Press d │ show developer tools
› shift+d │ toggle auto opening developer tools on startup (enabled)

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
Started Metro Bundler
Error: Problem validating asset fields in app.json. Learn more: https://docs.expo.dev/
 • Field: icon - field 'icon' should point to .png image but the file at './assets/Bee-Logo.jpg' has type jpg.
 • Field: android.adaptiveIcon.foregroundImage - field 'android.adaptiveIcon.foregroundImage' should point to .png image but the file at './assets/Bee-Logo.jpg' has type jpg.
info Launching Dev Tools...
Error: Problem validating asset fields in app.json. Learn more: https://docs.expo.dev/
 • Field: icon - field 'icon' should point to .png image but the file at './assets/Bee-Logo.jpg' has type jpg.
 • Field: android.adaptiveIcon.foregroundImage - field 'android.adaptiveIcon.foregroundImage' should point to .png image but the file at './assets/Bee-Logo.jpg' has type jpg.
Android Bundling complete 8451ms`

**Comment by Mitchell139** [comment]
Installed latest android build and it's still crashing
https://expo.dev/accounts/dltx/projects/IDEM/builds/90e03771-0b91-43e6-ae5d-911f82c00d86
