### ISSUE TITLE
Typescript dependencies missing

### ISSUE THREAD

**Issue by Mitchell139** [dltxio/idem-mobile#206]
Prompted to install additional dependencies when running `yarn start` in `app`
![image](https://user-images.githubusercontent.com/50130291/176367606-4afea309-0e93-4a26-9fcb-9cbd9bfde6f2.png)

**Comment by bitcoinbrisbane** [comment]
Getting similar

![image](https://user-images.githubusercontent.com/8411406/176980363-91f72e02-ac02-4276-8d66-5cec322b1c8b.png)

**Comment by JasminFarhi** [comment]
Fixed issue with Mitch, does not seem to be a global issue

**Comment by C00p3rb123** [comment]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/48899363/180695423-8a6f3e8b-7271-419d-a4d0-7f0cdf937a72.png">

**Comment by JasminFarhi** [comment]
Updated the readme with instructions for

**Comment by brettvniekerk** [comment]
Only prompted to update expo-cli, but no dependency notification on clean install
