### ISSUE TITLE
As a user, I want to input data in an efficent way, so that I can use the app

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#216]
## Context
iOS has 12 different keyboards depending on the context.  Change the keyboard type to match the claims type

https://betterprogramming.pub/12-shades-of-keyboard-types-in-ios-a413cf93bf4f

**Comment by C00p3rb123** [comment]
Postcode should be a numerical keyboard
![image](https://user-images.githubusercontent.com/48899363/177084068-71535085-c1d8-408f-8899-6810fbe5a50d.png)

**Comment by JasminFarhi** [comment]
Change street number in address - from showcase
