### ISSUE TITLE
As IDEM I want my verfied claims signed with IDEM ethereum address so I can use them on other services

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#227]
- Given I have all my claims
- When I verify my claims via the proxy
- Then I receive a WC3 VC signed by IDEMs Ethereum address

## Test Step
Using POSTMAN
sending `POST` request to `https://uat-proxy.idem.com.au/user/verify`
Set body to
 ```json
{
  "firstName": "string",
  "middleName": "string",
  "lastName": "string",
  "dob": "string",
  "email": "string",
  "houseNumber": "string",
  "street": "string",
  "suburb": "string",
  "postcode": "string",
  "state": "string",
  "country": "string"
}
```

Set Authorization to `Basic Auth`
username : myusername
password : password123

result should contain `verifiableCredential` and `signedMessage`

**Comment by C00p3rb123** [comment]
blocked by #292

**Comment by pondpiu** [comment]
Follow up @xiangzhe0812 on progress,
can be test via postman without waiting for 292

**Comment by pondpiu** [comment]
endpoint is up at `/user/verify`

**Comment by C00p3rb123** [comment]
blocked by #317

**Comment by pondpiu** [comment]
![image](https://user-images.githubusercontent.com/10498040/181681465-25fd3691-ec58-417c-9c1a-9c97b7932b5f.png)

**Comment by JasminFarhi** [comment]
![Screen Shot 2022-08-30 at 12 59 12 pm](https://user-images.githubusercontent.com/83386965/187339031-38635b05-b4cf-42f5-a1fb-df0dd833b7fa.png)

**Comment by JasminFarhi** [comment]
Screen shot of a Singed claim above
