### ISSUE TITLE
As GPIB I want users to signup and verify with an IDEM QR code so they be onboarded

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#228]
- Given I have scanned the generated QR code
- When I scan the QR code
- Then I will be taken to the Supported exchanges page and prompted to signup and verify with GPIB

## Testing notes

Run IDEM native build from TestFlight

idem://exchange/vendors/1
Then go to https://www.qrcode-monkey.com/
Create the QR code and scan it with your phone
you should be taken to the GPIB page in supported exchanges 

https://testv2.getpaidinbitcoin.com.au/register

**Comment by pondpiu** [comment]
Waiting for https://github.com/dltxio/proxy.idem.com.au/pull/17 to be merged

**Comment by pondpiu** [comment]
Deeplinking already working with `idem://exchange/vendors/1`
only need to generate QR code and put on GPIB site

**Comment by pondpiu** [comment]
Example QR code [idem://exchange/vendors/1]
![qr-code](https://user-images.githubusercontent.com/10498040/177687587-fb8b7d26-ac1a-4017-8afe-6c5812e63531.png)

**Comment by Mitchell139** [comment]
Testing steps don't work.

If you use idem://exchange/vendors/1 (found it in slack somewhere), the user isn't "taken to the Supported exchanges page and prompted to signup and verify with GPIB"

**Comment by Mitchell139** [comment]
Worked a couple times but more often than not it would just crash. A few screenshot of it crashed/frozen: 
![Screenshot_20220707-175341_idemID.jpg](https://user-images.githubusercontent.com/50130291/177723249-942e13d3-8bf7-4998-8ecf-9481422f70de.jpg)
![Screenshot_20220707-175856_idemID.jpg](https://user-images.githubusercontent.com/50130291/177723225-221b0d3f-cc47-4912-90c1-0600071632b3.jpg)

**Comment by Mitchell139** [comment]
Still crashing a majority of the time
![Screenshot_20220714-132557_idemID.jpg](https://user-images.githubusercontent.com/50130291/178891786-6df268da-6523-4ebb-92d3-252db35e53bb.jpg)![Screenshot_20220714-132631_idemID.jpg](https://user-images.githubusercontent.com/50130291/178891791-bd6cc1bc-4bd2-423b-8944-bbf8649ea670.jpg)![Screenshot_20220714-132648_idemID.jpg](https://user-images.githubusercontent.com/50130291/178891797-05e4a884-1983-486c-8f36-69dc389fe8d4.jpg)

**Comment by pondpiu** [comment]
only happen with dev-client build on my android
local expo-go and native build works normally

**Comment by pondpiu** [comment]
as per discussion in the morning, should test this on native build

**Comment by pondpiu** [comment]
TestFlight build is broken, need to be fixed first. https://github.com/dltxio/idem-mobile/issues/255

**Comment by C00p3rb123** [comment]
blocked by #255 - unable to test on testflight
