### ISSUE TITLE
As an IDEM user, I want my Mnemonic stored in the Universal Wallet Format, so that my seed is to the DID standard

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#233]
## Context
The DID has a spec for storing Mnemoics.  The app should use this standard. https://w3c-ccg.github.io/universal-wallet-interop-spec/#Mnemonic

## AC
- Given
- When
- Then

```json
{
  "@context": ["https://w3id.org/wallet/v1"],
  "id": "c410e44a-9525-11ea-bb37-0242ac130002",
  "name": "My ETH Mnemonic 1",
  "type": "Mnemonic",
  "value": "humble piece toy mimic miss hurdle smile awkward patch drama hurry mixture"
}
```

**Comment by C00p3rb123** [comment]
Testing/Demo Steps:

1. Ensure you currently do not have mnemonic seed
2. Insert: console.log(wallet) into line 51 in useMnemoonic.ts _(app\src\hooks\useMnemonic.ts)_
3. Create mnemonic seed
4. Check console/terminal and ensure that the "wallet" has the same format as the AC.

**Comment by C00p3rb123** [comment]
After speaking with @bitcoinbrisbane , I have just altered the JSON object to match what IDEM needs
