### ISSUE TITLE
Alert dialog should say Success! on registration.

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#237]
## Context
On a successful registration, the alert should say "Success!" rather than "Register" to be consistent. 

![image](https://user-images.githubusercontent.com/8411406/177675102-902bc3ee-97bc-4f6a-98dc-ef08f485acdd.png)

**Comment by C00p3rb123** [comment]
Receiving HTML script as my response for coinstash. I received another error for GPIB however I was unable to load the screenshot for GPIB. 

![image](https://user-images.githubusercontent.com/48899363/177709704-a393f9b8-8a93-4fc0-b20f-913321e16590.png)

**Comment by pondpiu** [comment]
the whole response
https://gist.github.com/pondpiu/5ffbadecab1fc70f09797efd23fe3fd9

![image](https://user-images.githubusercontent.com/10498040/177714782-f7a37f55-3a9f-4805-b906-4ecf922175fb.png)

**Comment by bitcoinbrisbane** [comment]
They might have put in some DDoS protection?

**Comment by Mitchell139** [comment]
Blocked until [this](https://github.com/dltxio/idem-mobile/issues/193#issuecomment-1177065919) gets fixed so we can test with GPIB
