### ISSUE TITLE
As IDEM, I want to lock my email once verified, so that the app cant be gamed.

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#239]
## Context
Once a user has verifed their email via the PGP public key server, the app should not allow the user to modify the email.  If they want to change it, the can simply delete the app.

Requires #11 

## AC
- Given a user,
- When when their email is veified,
- Then they're not able to modify the email claim

**Comment by JasminFarhi** [comment]
Testing Notes 
Create temp email - https://www.emailondeck.com/eod.php
Create PGP - https://www.attogtech.com/pgp-key-generator/
- in the app add your email claim and paste your public block into the PGP paste block 
- Click publish public key 
- go to your email and click the verification link
- go back to the app and click verify email which should say "success" 
- go back to claims list and into email, and the button should be disabled :)

**Comment by C00p3rb123** [comment]
Followed testing steps and button is disabled 

Currently unable to test if it works when the PGP is automatically generated (dependent on #9 to be working)

Unable to test if it works when I have my own private key because of #340

**Comment by Mitchell139** [comment]
Testing blocked because currently unable to publish PGP key https://github.com/dltxio/idem-mobile/issues/9#issuecomment-1211691118

**Comment by Mitchell139** [comment]
Can't verify email https://github.com/dltxio/idem-mobile/issues/9#issuecomment-1219061374
