### ISSUE TITLE
Import PGP key doesn't work

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#243]
Given I haven't imported a PGP private key
When I paste my PGP private key into the text box and click "Import my private key" 
Then it returns the error "UH-OH"

<img src="https://user-images.githubusercontent.com/83386965/178630553-622f5bad-346d-4327-b94b-81ef0a39c20f.png" width="300" />

# Testing Note
- not working on expo development build
- need to test on native app build

**Comment by bitcoinbrisbane** [comment]
Relates to #11

**Comment by pondpiu** [comment]
`react-native-fast-openpgp` lib IDEM currently use don't support expo
seems to be working fine once built into native app,
![](https://files.slack.com/files-pri/T01AS5WKKGX-F03P7EX4UQM/screenshot_20220713-162827.png)
