### ISSUE TITLE
As a user, I want to verify my phone number so that I can signup to exchanges using IDEM

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#245]
**AC**
Receiving verification code
- Given I am on the mobile claim page and have entered my phone number 
- When I tap the "Verify" button (Currently "Save")
- Then I will receive a verification code 

**Devs steps**
When a user hits verify, sign a payload and post the the proxy https://proxy.idem.com.au/verify/mobilenumber

The proxy will then generate a HMAC-256 hash

Payload
```json
{
   "mobilenumber": "+61000000"
}
```
- Then the system posts the information to the server
- And the server alerts the user an OTP verification via SMS

![image](https://user-images.githubusercontent.com/91101134/180133618-bd9e65d1-2b2d-443e-a54d-eaeb6eea7669.png)

## Test steps
Make sure that both https://github.com/dltxio/idem-mobile/pull/289 and https://github.com/dltxio/proxy.idem.com.au/pull/23 is already merged

test API via `https://proxy.idem.com.au/swagger` and send request to `/user/requestOtp`
test mobile by going to main Profile page -> Mobile Claims -> enter number and click verify

you should receive 6 digit OTP code via SMS for both case

**Comment by pondpiu** [comment]
- IDEM proxy endpoint
- Redis instance
- SMS provider

**Comment by pondpiu** [comment]
SMS provider : https://developers.messagebird.com/
Look into `Verify` service first, if it doesn't match our use case then fallback to SMS with our own OTP implementation

**Comment by xiangzhe0812** [comment]
@Mitchell139 @C00p3rb123  Pls test on IOS, Alert.prompt not support android.

**Comment by C00p3rb123** [comment]
Blocked by #317

**Comment by C00p3rb123** [comment]
Error when testing on mobile 

![image](https://user-images.githubusercontent.com/48899363/181441380-2a870cd6-ff64-4d5f-ad11-1dd2f2f4e5e7.png)

**Comment by xiangzhe0812** [comment]
@C00p3rb123 @Mitchell139  waitting for switching to uat PR get merged, I guess that is the problem.
try agin once the https://github.com/dltxio/idem-mobile/pull/313 merged.
