### ISSUE TITLE
As IDEM I want to capture users email addresses so I can contact them later

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#246]
## Context
Capture some potential users for IDEM

## AC
- Given I am on idem.com.au
- When I input my first name, last name and apple ID on the idem website 
- Then it will be captured and stored into the proxy db

https://docs.fastlane.tools/actions/pilot/

**Comment by JasminFarhi** [comment]
FYI this ticket has two PR's one on IDEM-MOBILE and one on IDEM-PROXY, plz don't move till both are approved :)

**Comment by JasminFarhi** [comment]
Testing notes 
On the Idem website, there are some input fields for interested users to try out idem. 
pop your details in and it should send to the backend, there is a table in the DB that should hold all this info you can double-check.

**Comment by JasminFarhi** [comment]
Requirments have changes based on the clients requests... 
We now only need 
first name input 
last name input 
email (apple ID) input and submit 
this is then being set to the proxy and being stored in the DB

**Comment by C00p3rb123** [comment]
Auto-filling details causing data capturing process to break. 

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/48899363/181423038-aef23cea-1291-4a6f-920c-0aff351c1c00.png">

**Comment by C00p3rb123** [comment]
Can't enter any data without receiving an error

<img width="1534" alt="image" src="https://user-images.githubusercontent.com/48899363/181441885-e3507ed8-8818-45e4-b796-77db8e99eb2a.png">

**Comment by JasminFarhi** [comment]
Disabling auto fill does not fix the issue. When testing please dont use auto fill for the input fields

**Comment by C00p3rb123** [comment]
Experiencing same issue as above - no autofill

Tried using different browsers and checked if anything in storage was causing it

**Comment by C00p3rb123** [comment]
Working both normally and with auto fill 💯
