### ISSUE TITLE
As an IDEM user I want to create an account on Digital Surge so that I can use their service and have my details filled out for me 

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#247]
## Context
We will need to post to our proxy.idem.com.au then the proxy will call their partner API.  Relates #415, #407 and #392 

Singing up
- Given I have verified my email and phone number
- When I tap "Signup" in the Digital Surge's supported exchanges page
- Then I will be signed up to Digital Surge and will receive a temporary password in the IDEM app

Trying to sign up with not enough claims verified 
- Given I have not verified either my email or phone number
- When I am on the Digital surge's supported exchange page
- Then the "Signup" button will be disabled

@Mitchell139 @C00p3rb123  digital surge's partner api is test environment at moment, so we can't really login to the site.
In the meantime I will send email to ask if we can have the test site like GPIB so we know its working.
Testing steps 
1. click the signup on vender screen
2. expect receive password
3. db will save the request like below
<img width="1141" alt="Screen Shot 2022-09-01 at 2 26 14 pm" src="https://user-images.githubusercontent.com/1115763/187831379-74bed952-5419-4db7-9c8c-d24e88fe93dc.png">

4. also if you resignup with same email you will get message like below, i believe its good enough for now.
![IMG_4277](https://user-images.githubusercontent.com/1115763/187831561-89da8830-fd79-4e09-aca3-b767bdbfee03.png)

**Comment by TomDodson** [comment]
Why no proxy in this ticket @pondpiu @JasminFarhi?

**Comment by pondpiu** [comment]
Blocked : Waiting for proxy implementation detail from @bitcoinbrisbane & Digital Surge

**Comment by pondpiu** [comment]
The details are in

**Comment by C00p3rb123** [comment]
Blocked by #352 - unable to verify mobile

**Comment by C00p3rb123** [comment]
**Signing up**

- When clicking on sign up after entering all claims and clicking "Verify All Claims", I receive an error (image below)
- I have access to this button without verifying my email address.
 
![image](https://user-images.githubusercontent.com/48899363/184267765-298411fa-d933-42b5-a76c-7200a917fa93.png)

**Comment by pondpiu** [comment]
Same problem with https://github.com/dltxio/proxy.idem.com.au/issues/24

**Comment by Mitchell139** [comment]
Can't verify email https://github.com/dltxio/idem-mobile/issues/9#issuecomment-1219061374

**Comment by C00p3rb123** [comment]
Should wait until we can login into a test site before this moves to staging, however everything is working as expected

**Comment by C00p3rb123** [comment]
Blocked until we have solution to being able to login to a digital surge site

**Comment by xiangzhe0812** [comment]
@Mitchell139 @C00p3rb123  https://sita.digitalsurge.io/ url for DS signup

**Comment by C00p3rb123** [comment]
Currently able to sign up to Digital Surge with an unverified email address. However changes to enforce verification for Digital Surge will occur in #392, #415 and #407. 

Sign up process is working and user is able to log in to the digital surge test site.
