### ISSUE TITLE
CoinTree bugs

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#252]
- Change colour
- Fix text (duplicated)  
- Should be CoinTree

![File (1)](https://user-images.githubusercontent.com/8411406/178883806-4de0da46-a0ad-4f36-af6f-def407f5f08d.jpg)

**Comment by Mitchell139** [comment]
Colour hasn't been changed (still white background)
Most of the logo is cut off

**Comment by bitcoinbrisbane** [comment]
I made the colour to be white

**Comment by JasminFarhi** [comment]
- adjusted colour
- Fix text (duplicated)
- adjusted name to "cointree"
- having issues with adjust image size from json

**Comment by C00p3rb123** [comment]
Colour is still white - if this is correct it can be moved back to testing
