### ISSUE TITLE
Build breaking to testflight on IOS

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#255]
<img width="1218" alt="Screen Shot 2022-07-14 at 3 16 23 pm" src="https://user-images.githubusercontent.com/83386965/179120428-b9f5e4f1-272c-4645-aeb3-dc2149301d93.png">
<img width="1218" alt="Screen Shot 2022-07-14 at 3 18 56 pm" src="https://user-images.githubusercontent.com/83386965/179120438-3601b60e-2af2-4366-a5ef-8271a14de758.png">

**Comment by pondpiu** [comment]
Latest change before build breaking is before adding `expo-document-picker`

According to installation documentation https://docs.expo.dev/versions/latest/sdk/document-picker/
revoking provisioning profile is needed

**Comment by C00p3rb123** [comment]
Current version is 1.0.79 and on Testflight I only have access to 1.0.60

**Comment by JasminFarhi** [comment]
https://help.apple.com/app-store-connect/#/dev88f5c7bf
<img width="1071" alt="Screen Shot 2022-07-15 at 3 37 16 pm" src="https://user-images.githubusercontent.com/83386965/179158091-2bae8790-ae4a-49d1-954a-4784fbc6cf2f.png">
9

**Comment by pondpiu** [comment]
Build pipeline is working now, but TestFlight is not publishing new version due to compliance questionnaire (+ documents?)
@bitcoinbrisbane @amagon270

**Comment by bitcoinbrisbane** [comment]
> Build pipeline is working now, but TestFlight is not publishing new version due to compliance questionnaire (+ documents?) @bitcoinbrisbane @amagon270

These builds we're not encrypting.
