### ISSUE TITLE
PGP key can also contain public key

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#269]
## Context
Exporting PGP keys can contain both private and public in the text file.  The below validation is not correct.
https://github.com/dltxio/idem-mobile/blob/main/app/src/navigation/screens/PGPScreen.tsx#L35-L41

## AC
- Given a user with a PGP private and public key,
- When I import that file,
- Then my key is added

## Test steps
-  Export a PGP public and private key gpg --export-secret-key -a "User Name" > private.key
- Add to cloud storage like iCloud
- Attempt to import

**Comment by C00p3rb123** [comment]
Attempted to import and received this message: 


![image](https://user-images.githubusercontent.com/48899363/180695245-fd5dcf8b-d11b-4b8b-9d69-f14e523ae426.png)

**Comment by pondpiu** [comment]
Works on my device,
can you check whether the file contain valid private key? @C00p3rb123
