### ISSUE TITLE
As IDEM, I want to create a KECCAK hash of my document, so that I can use it as part of the VC payload

### ISSUE THREAD

**Issue by ahinchliff** [dltxio/idem-mobile#27]
When a user selects their document, create a KECCAK hash of the document that is displayed below the image of the file.

**Comment by JasminFarhi** [comment]
![Image from iOS (46)](https://user-images.githubusercontent.com/83386965/171309595-1203fc35-2d64-4546-b0f0-a46b4e9489e0.jpg)
Is it meant to be KECCAK265 or 256?

**Comment by bitcoinbrisbane** [comment]
256 https://medium.com/0xcode/hashing-functions-in-solidity-using-keccak256-70779ea55bb0

**Comment by bitcoinbrisbane** [comment]
> Can't test. Blocked by #70

This is why we need to change to the aleart with a cancel @jrocca82 #13
