### ISSUE TITLE
SPIKE: Investigate mobile verification using GreenID

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#276]
- See if GreenID provides a mobile verification service
- How does the verification service work?

Relates to #41 #277

**Comment by pondpiu** [comment]
GreenID API doc
https://vixverify.atlassian.net/wiki/spaces/GREEN/pages/60368141/Web+Method+Details+V3#WebMethodDetailsV3-RegisterVerification

**Comment by pondpiu** [comment]
There is `mobilePhone` parameter in `RegisterVerification` endpoint but i don't see any otp related stuff. Not sure how they going to verify it.

**Comment by pondpiu** [comment]
Looks like they are doing background check and info lookup against their Database only.
Probably need to implement ourselves using provider like https://developers.messagebird.com/
