### ISSUE TITLE
As auser, I want to request my mobile number to be verified, so that I will receive an OTP for verification

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#277]
## Context
Add the verify button back to the mobile claims view.

**Comment by pondpiu** [comment]
Server
- need to add salt to prevent attacker to try to rehash locally
- some mechanism to prevent brute-force otp code

**Comment by bitcoinbrisbane** [comment]
> Server
> 
> * need to add salt to prevent attacker to try to rehash locally with the same algorithm
> * some mechanism to prevent brute-force otp code

100%.  The HMAC on server should have a salt.
Re brute force, we should / will role out some basic auth on our proxy apis soon.

**Comment by pondpiu** [comment]
Wait for https://github.com/dltxio/idem-mobile/issues/276
