### ISSUE TITLE
As Idem I want to record a screen capture that runs through the app so we can use the footage to create a promotional video for Idem.

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#283]
Record a screen capture that runs through the app so we can use the footage to create a promotional video for Idem.

https://youtu.be/M_wreVz4vcs

**Comment by Mitchell139** [comment]
@JasminFarhi Where video?

**Comment by bitcoinbrisbane** [comment]
On my Mac. Will be a week or so

**Comment by JasminFarhi** [comment]
The video is located in the Idem slack channel
