### ISSUE TITLE
Get on the app store

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#284]
## Context
Check list to go live https://developer.apple.com/app-store/review/guidelines/

Appstore copy: 

https://bitcoinbrisbane-my.sharepoint.com/:w:/g/personal/tom_dodson_dltx_io/Ef6-heDJYoVJuFdv_uEMn6IB-vtwINS_wou12rFzNaem6Q?e=yhmfau

**Comment by pondpiu** [comment]
Todo List
- [ ] seperate UAT & PROD proxy endpoint
- [ ]

**Comment by pondpiu** [comment]
Technical part looks ready.
Sending off to @TomDodson to fill in app details on `https://appstoreconnect.apple.com/`

**Comment by JasminFarhi** [comment]
Waiting to hear back from apple about mobile verification
