### ISSUE TITLE
As a user verifying mobile, I want to put in OTP so that my mobile can be verified

### ISSUE THREAD

**Issue by jinggg-y** [dltxio/idem-mobile#285]
## Context
After the user fills in their mobile number the system will deal with OTP alert #277.  Meanwhile, the app will respond to the verification 

## AC
- Given I have hit the verify button received my OTP 
- When the app shows the OTP page
- Then I will I will enter in the code within the timeout period
- Then my mobile number is verified
- Then I will receive a success alert "Your mobile has been verified"

Verification code invalid
- Given my verification code is invalid or has timed out
- Then I receive an alert stating "Please try again, verification code invalid"

## Test steps
-

**Comment by C00p3rb123** [comment]
Blocked by #317

**Comment by C00p3rb123** [comment]
Blocked by error in #245 - have not received my OTP

**Comment by C00p3rb123** [comment]
No alert for entering OTP after the timeout period has ended
