### ISSUE TITLE
As an IDEM I want to post a users document metadata to the proxy so it can be verified with GreenID

### ISSUE THREAD

**Issue by jinggg-y** [dltxio/idem-mobile#288]
## Context
Each exchange request different claims to be KYC verified

- Given I am on the exchange page and I have all the required claims to signup
- When I tap "Sign up"
- Then my unverified claims and documents will be posted to the proxy to be verified with GreenID

## Test steps
-

**Comment by TomDodson** [comment]
Awaiting greenID signup
