### ISSUE TITLE
Users are allowed to sign up with potentially invalid email addresses

### ISSUE THREAD

**Issue by brettvniekerk** [dltxio/idem-mobile#303]
## Context
![Image from iOS](https://user-images.githubusercontent.com/79682833/180919075-5b2bd25c-76e0-48d8-8a63-1e6b79a59f40.jpg)

No apparent for validation of email fields. Allows creation of names with special characters, and emails that don't adhere to email format.

test steps
- please type in an incorrect format for email address 
- example 1 "test.com"
- example 2 "test@
- example 3 "test"

Use: ```@"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z"```

**Comment by bitcoinbrisbane** [comment]
Use the regex ```@"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z"```

**Comment by TomDodson** [comment]
Need to broken down into separate issues, one for email and one for name

**Comment by JasminFarhi** [comment]
We have decided to use validator js as we have used it before in previous projects. much easier and simpler than regex.

**Comment by Mitchell139** [comment]
See: https://github.com/dltxio/idem-mobile/issues/468#issuecomment-1246215263

**Comment by C00p3rb123** [comment]
- Names are not validating 
- Email validation is occurring but should happen when a user clicks "set up pgp key" and not "verify"

**Comment by Mitchell139** [comment]
Insufficient test steps

- Names are not being validated
- Shows an alert if user enters invalid email but saves it anyway

**Comment by Mitchell139** [comment]
Test steps still wrong 

Name validation doesn't seem to be working? But idk because of aforementioned test steps
![image](https://user-images.githubusercontent.com/50130291/191880461-6f110fd0-b3be-4857-b897-9e45c65ab887.png)

**Comment by Mitchell139** [comment]
Insufficient AC / test steps 

Error message is poorly worded
![image](https://user-images.githubusercontent.com/50130291/191881184-79aeb310-4b10-4297-8c55-82daf6b4f1af.png)

**Comment by xiangzhe0812** [comment]
@Mitchell139  fixed on #501

**Comment by Mitchell139** [comment]
Error message is poorly worded
![image](https://user-images.githubusercontent.com/50130291/191897645-be38d8f2-d243-4c9c-9b07-28639674195e.png)
