### ISSUE TITLE
Digital Surge logo got cut off

### ISSUE THREAD

**Issue by jinggg-y** [dltxio/idem-mobile#315]
![image](https://user-images.githubusercontent.com/62837203/181415132-09eff752-4a4e-4e0f-a617-c8b939c84f23.png)

Changes have been fixed for this bug on ticket #252

**Comment by bitcoinbrisbane** [comment]
Need new screenshot @JasminFarhi

**Comment by C00p3rb123** [comment]
Latest pull as of 11:27am didn't seem to have changes?
![image](https://user-images.githubusercontent.com/48899363/182055422-a1ae646c-2683-4c86-a2bd-bf0ff3de8185.png)
