### ISSUE TITLE
As an IDEM user, I want to add a photo from my camera roll to a document type, so that I can use it as a proof

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#32]
The app can add evidence by the way of documents to a claim.  The user can select a previously taken photo.

- Given a user
- And they click documents
- And they select Passport
- When the hit "Select From Camera Roll"
- Then they are show the devices photos to select

![image](https://user-images.githubusercontent.com/8411406/170382524-2b8d607a-94f6-4cf4-9ff1-9d9d7a1a05ef.png)

**Comment by Mitchell139** [comment]
@JasminFarhi Please test on iOS
