### ISSUE TITLE
The documents page responsive bug

### ISSUE THREAD

**Issue by jinggg-y** [dltxio/idem-mobile#328]
On iPhone 12 mini, the last button got cut off, and the page is not scrollable. 
The page may need to be resized and adapted to different screen sizes. 
![Screenshot 2022-08-01 170108](https://user-images.githubusercontent.com/62837203/182091082-34b399b9-bbbc-4d20-8322-9c64e1dc402b.png)

**Comment by JasminFarhi** [comment]
Still happening on Jings phone

**Comment by jinggg-y** [comment]
Bug solved
