### ISSUE TITLE
As IDEM I want to use our own repo images for exchanges so we can resize them to fit the IDEM app

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#331]
- Each image for each exchange needs to be organized and added to the repo instead of getting the images from URLs 
- Each of the images needs to be reformatted so that they are centered and fit the screen

**Comment by C00p3rb123** [comment]
Seems like old designs are still present

![image](https://user-images.githubusercontent.com/48899363/182758403-343d1c84-e2a3-4ff1-a640-88dd3d861c9d.png)
![image](https://user-images.githubusercontent.com/48899363/182758423-75f74a3e-9def-4b79-b62c-d33aa8419bc5.png)
![image](https://user-images.githubusercontent.com/48899363/182758437-bc63c88b-275e-402f-bee9-65e75985592d.png)
![image](https://user-images.githubusercontent.com/48899363/182758450-c40a795c-a8bd-4b41-a06c-d5e8cf14b1a8.png)

**Comment by C00p3rb123** [comment]
coinstash missing logo
