### ISSUE TITLE
As IDEM, I want to ensure that when something goes wrong in the app, it's been reported so that we can investigate

### ISSUE THREAD

**Issue by pondpiu** [dltxio/idem-mobile#336]
## Context
IDEM mobile app don't have observability into app error yet

## AC
- Given I am using IDEM mobile app (UAT & PROD built)
- When The app encounter an unexpected error
- Then the error is reported to Monitoring Service

## Test steps
-  consult with dev to create buggy built on testFlight built
- check whether the error is reported to the service (sentry)

**Comment by pondpiu** [comment]
Blocked by #338

**Comment by C00p3rb123** [comment]
I was experiencing bug #352 and sentry did not update 

![image](https://user-images.githubusercontent.com/48899363/183334431-6e4e2dcd-da84-41cd-a932-424bc6953abf.png)

**Comment by pondpiu** [comment]
Because we store sentry secret token at expo server, local & development build error won't be reported to sentry because they lacks sentry token

**Comment by pondpiu** [comment]
We could manually put sentry token in to test on development build

**Comment by C00p3rb123** [comment]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/48899363/184050407-99107aca-1485-413e-bea0-cd1c3b93da06.png">

**Comment by C00p3rb123** [comment]
Same error as above
