### ISSUE TITLE
As IDEM, I want to automatically update the third parties list, so I don't need to redeploy the app each time

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#35]
Use a blob json in GitHub to provide data for the third parties page.   The app will simply fetch this data and bind to the list of 3rd parties on the 3rd parties tab.  GH will allow 3rd parties to update via a PR

- Given an admin
- When I update the 3rd parties list
- And refresh the 3rd parties list
- Then I see the new site in the list

Eg blob

```bash
curl https://raw.githubusercontent.com/dltxio/idem-mobile/IDEM-35/data/sites.json
```
![jehnwMtbG6uMhZYFDm3p5J](https://user-images.githubusercontent.com/8411406/172087619-768d03bb-428e-425b-a4f6-ed6d1fac7703.png)

**Comment by Mitchell139** [comment]
Looks like there's two different json files for adding sites? 
![image](https://user-images.githubusercontent.com/50130291/172313769-9d634632-dd48-436f-8564-56f578d7b281.png)
![image](https://user-images.githubusercontent.com/50130291/172313815-13e121c5-d6a5-414f-beeb-a35b2efe87c8.png)

**Comment by bitcoinbrisbane** [comment]
Nice one!  Ill fix

**Comment by Mitchell139** [comment]
Made and merged PR to add a new test exchange but it's not showing up in the list. https://github.com/dltxio/idem-mobile/pull/94

**Comment by bitcoinbrisbane** [comment]
Back button on the top left should say "3rd Parties" or similar not vendors list

![image](https://user-images.githubusercontent.com/8411406/172533171-fe4adbb7-d74f-459d-b145-be10f1895c55.png)

**Comment by Mitchell139** [comment]
The two jsons for adding sites hasn't been fixed: https://github.com/dltxio/idem-mobile/issues/35#issuecomment-1148267337

**Comment by jrocca82** [comment]
@bitcoinbrisbane can we talk about what we want to do about the double json?
