### ISSUE TITLE
Unable to verify mobile number

### ISSUE THREAD

**Issue by C00p3rb123** [dltxio/idem-mobile#352]
## Context

When clicking on "Verify" after entering a mobile number, an error returning - "statusCode:".401"  prevents the verification process from completion. 

![image](https://user-images.githubusercontent.com/48899363/183331530-97b1daec-0f56-4e27-8c8a-a780e4369a3d.png)

![Inkedimg_0119](https://user-images.githubusercontent.com/48899363/183331967-0084bb34-41d8-42d6-aef7-de1780608d85.jpg)
![image](https://user-images.githubusercontent.com/48899363/183331998-637b7949-9dac-4e71-968d-e7d16bcd5025.png)

**Comment by bitcoinbrisbane** [comment]
![image](https://user-images.githubusercontent.com/8411406/184284729-37d1997d-5bee-43a4-a124-6583aca5e9be.png)

**Comment by darrenrogan** [comment]
I get the same error as @bitcoinbrisbane when trying to verify my mobile (also on iOS)

**Comment by xiangzhe0812** [comment]
@darrenrogan  it's woking now, pls download the latest version from testflight.

**Comment by Mitchell139** [comment]
Need to add instructions to enter credentials into readme

**Comment by xiangzhe0812** [comment]
@Mitchell139 @C00p3rb123  Technically should not using local build or running locally to test, same as other projects testing on UAT, I will add instruction how to get latest uat build into readme.

**Comment by Mitchell139** [comment]
@xiangzhe0812 I don't need instructions on how to test it. I moved this back because there aren't any instructions in the readme that the dev/whoever is trying to run the app has to go to some random file and enter in the message bird credentials

**Comment by xiangzhe0812** [comment]
@Mitchell139 That is what Im trying to explain to you, you shouldn't run the app locally to test, all of the creds builded in whe ran the new build, you and @C00p3rb123  just need download/update the app from testflight or expo dev(for android) and test.
