### ISSUE TITLE
As a user I want to join GPIB with a single click so I can easily use the platform

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#377]
## Context
Currently, the user has to signup and then "sync" their details to signup and verify themselves on GPIB. This will make it just "one-click" where the user is signed up and verified just by pressing one button.

## AC
- Given I am on the GPIB exchange page in the idem app
- When tap signup
- Then I will be fully verified and signed up to GPIB

## Test steps
-

**Comment by C00p3rb123** [comment]
Blocked by #352 - not able to verify mobile number

**Comment by C00p3rb123** [comment]
GPIB Signup not working properly
![image](https://user-images.githubusercontent.com/48899363/187124036-d5f4fa4e-3d7f-462c-a06a-d2caf025e77a.png)
