### ISSUE TITLE
As IDEM I want a clean and tidy UI so I can show off the app to users 

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#386]
- Buttons all need to be the same across the entire app
- A flat list for items needs to be the same on the profile page as on the exchange page 
- All capitals for private?
- Instead of Import my Private Key from my Device, it should be Import Private Key from Device (discussion around importing workflow perhaps required)
- Should be "Generate New PGP Key"
- Should be "Verify Email"
- Instead of "Import", @bitcoinbrisbane suggested it should be "Set"
- "Your claims" and "All claims" should have a capital c
- Should be "Date of Birth"
- status bar at the top of android needs to show 
- nav bar title "Supported Exchanges" should just be "Exchanges" and supported should be a title above the exchanges 

**Button Title Standard for IDEM**
Book title standard where words are capitals unless they are a preposition.

![image_from_ios](https://user-images.githubusercontent.com/48899363/186542051-e7b78541-5c98-4250-b2f8-30a599756bf0.png)

![image_from_ios (1)](https://user-images.githubusercontent.com/48899363/186546054-165e2dad-4eb3-4d56-a1e4-16a9971be1fd.png)

![image_from_ios (2)](https://user-images.githubusercontent.com/48899363/186546813-b2a4348a-06b1-4d5a-9978-5e75798d8344.png)

**Comment by C00p3rb123** [comment]
Generate New Pgp Key - for consistency 
"Tax file number" for consistency to match "Setup PGP key pair".

**Comment by C00p3rb123** [comment]
For consistency publish should have a capital P

![image](https://user-images.githubusercontent.com/48899363/186840457-6b2c9822-0181-4c80-aa14-2d79f94c3c4d.png)

**Comment by C00p3rb123** [comment]
Verify Email instead of Verfiy email

**Comment by C00p3rb123** [comment]
![image](https://user-images.githubusercontent.com/48899363/187124821-0c2cf027-dc1c-47aa-8bef-3fca4aa750e9.png)
