### ISSUE TITLE
As a new IDEM user, I want to verify my email, so that I can use IDEM on other services

### ISSUE THREAD

**Issue by jrocca82** [dltxio/idem-mobile#40]
There is no point reinventing the wheel.  We can use a PGP/GPG public key server to do this, and increase PGP adoption.

See #10 

- Given a user with an email,
- And they have a PGP/GPG key pair in the app,
- When I click "Verify Email Claim"
- Then I receive an email from https://keys.openpgp.org/ with instructions to verify my email

**Comment by jrocca82** [comment]
Only need to import public key for now:

**Comment by JasminFarhi** [comment]
I cant submit my public key cause the keyboard is blocking it. When I press return my keyboard does not disappear also for me to be able to do this. 

https://user-images.githubusercontent.com/83386965/173273329-ad3aa001-8383-4ffa-bcb7-47329f90ae8a.MP4

**Comment by JasminFarhi** [comment]
To test, please use this link - https://www.attogtech.com/pgp-key-generator/

**Comment by C00p3rb123** [comment]
- When initially clicking verify email, an error occurs. 
- Clicking it a 2nd time works however I never received an email to my dltx.io address. 
- I did receive an email to a .com address so it could be an issue sending to .io addresses. 

https://user-images.githubusercontent.com/48899363/173988200-cfbb7271-6b8c-4886-8420-cc5391cc237c.mp4

**Comment by jrocca82** [comment]
Can confirm searching for .io address on keys.openpgp.org leads to error on their API, nothing we can do
