### ISSUE TITLE
As IDEM I want to show Apple developers a video so they understand how our app works

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#403]
Before we can complete our review of your app, we need a video that demonstrates the current version, 1.0, in use on a physical iOS device showing the app pairing with the various exchanges within the app.

The demo video should:

- Show your app running on a physical iOS device, not on a simulator.

- Clearly documents all relevant app features, services, and user permission requests.

**Comment by bitcoinbrisbane** [comment]
Good one.

**Comment by JasminFarhi** [comment]
https://user-images.githubusercontent.com/83386965/187567422-21b1afcc-5f70-4027-93f7-bb69d991db7c.MP4

**Comment by Mitchell139** [comment]
@JasminFarhi So have they need it and ticked off whatever they need to tick off?
