### ISSUE TITLE
"Verification not found" error message to change

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#405]
Change the error text from "Verification not found" to "The required claims have not been verified. Please verify these claims on the profile page first."

- Given the user has their mobile, name, and email claim is filled in but is not verified. 
- When they click "Sign Up" on an exchange (GPIB) 
- Then the new error message will show. 
- And they won't be able to sign up. 

Relates #415 #407

**Comment by Mitchell139** [comment]
@JasminFarhi Need more details

**Comment by bitcoinbrisbane** [comment]
> Change the error text from "Verification not found" to "The required claims have not been verified. Please verify these claims on the profile page first."
> 
> * Given the user has their mobile, name, and email claim is filled in but is not verified.
> * When they click "Sign Up" on an exchange (GPIB) then the new error message will show.
> * Then they won't be able to sign up.

This whole flow will change with GreenID.  If the user doesn't have their name verified, we will do so "on the fly" for GPIB.

**Comment by bitcoinbrisbane** [comment]
![Untitled-2022-09-03-1121](https://user-images.githubusercontent.com/8411406/188251057-64fab736-563e-492e-8857-1e0447c9f74b.png)
