### ISSUE TITLE
As a user, I want the email input to be read only once verified so I don't get as confused by the "Save" button being disabled

### ISSUE THREAD

**Issue by Mitchell139** [dltxio/idem-mobile#411]
- Given I have verified my email address
- When I am on the email claims page
- Then the "Save" button will be disabled and the email will be read only

**Comment by C00p3rb123** [comment]
The cross next to the email will cause confusion. Any way we could remove it?

![image](https://user-images.githubusercontent.com/48899363/188038084-619890ae-29d1-493b-87cf-85cff91f011c.png)
