### ISSUE TITLE
As an IDEM user, I want to see the reset data button on my profile page, so it is clear what data I am resetting

### ISSUE THREAD

**Issue by jrocca82** [dltxio/idem-mobile#42]
As a user, I want to see the reset data button on my profile page, so it is clear what data I am resetting

- Given an IDEM user,
- And I navigate to the profile page,
- When I hit reset 
- Then ...

**Comment by bitcoinbrisbane** [comment]
Can also be reset by deleting the app

**Comment by bitcoinbrisbane** [comment]
@jrocca82 @TomDodson this needs an acceptance critiera better defined.

**Comment by bitcoinbrisbane** [comment]
Not required
