### ISSUE TITLE
As a potential GPIB user, when I sign up to the exchange then my claims are verified on the fly 

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#431]
## AC1 
- Given I have entered my email, name, and mobile credential 
- and my email and mobile have been verified by IDEM
- When I click sign up on GPIB 
- Then IDEM checks my name via GreenID (with the documents supplied to back up the name claim in ticket #BLAH)
- and the response is saved to my local storage as a WC3 claim signed by IDEM

## AC2 
- Given I have already been verified with Green ID 
- When I sign up for GPIB 
- Then my signed claims are posted to GPIB

![IDEM claims and KYC](https://user-images.githubusercontent.com/91101134/188352514-6e779606-0df7-4fa9-a0d5-32893fdb92cf.png)

**Comment by TomDodson** [comment]
@JasminFarhi
 _"Then IDEM checks my name via GreenID"_ GreenID does not work like this, you give it document metadata. Not just your name.
_"and the response is saved to my local storage as a WC3 claim signed by IDEM"_ Are we talking about the proxy or the IDEM app here? My understanding is that the proxy sign the claims in the WC3 shape.
