### ISSUE TITLE
As IDEM, I want to redesign the UI/UX for Documents screen so that we can include metadata for green ID requirements

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#438]
## AC1 

-Given a user has clicked on Documents on the navbar
-When they navigate to the Documents screen
-Then they can choose from the different Document options in the list (E.G. Drivers Licence, Medicare Card, Passport)
## AC2
-Given a user has clicked on a particular Document type 
-When they navigate to that screen
-Then they will see a screen specific to that Document type 
## AC3
-Given a user is on a specific Document screen 
-When they fill out the required input details 
-Then the save button will enable and they can save
## AC4
-Given a user is on a specific document screen and clicked the "Attach" button 
-When they choose an option from the list of options to upload a document (Options: "Select From Device", "Take A Photo", "Select From Camera Roll") 
-Then the document image/images will populate in the Files View Box. 
## AC5
-Given a user has uploaded a document from the "Attach" options
-When they click on the populated "Files" in the view box 
-Then they will be taken to the documents details screen 
## AC6
-Given a user has clicked the uploaded document from the "Files" view box 
-When they are on the document details screen
-Then they can see a list of information about the document (Details: Photo, Document Type, SHA256, KECCAK256)

<img width="746" alt="Screen Shot 2022-09-05 at 4 18 59 pm" src="https://user-images.githubusercontent.com/83386965/188380512-8f40e530-bee7-422c-bba1-a1fae62123ac.png">
<img width="316" alt="Screen Shot 2022-09-05 at 5 09 51 pm" src="https://user-images.githubusercontent.com/83386965/188386285-87f19d8d-513d-48cb-8129-74d3e89f5703.png">

**Comment by C00p3rb123** [comment]
**AC3**
Save button is enabled after not filling out required claims
Form state is saving without the save button enabled 
This is happening on passport, drivers licence and medicare card 

**AC4**
Can't attach documents from "Select From Device" and "Take a photo"
Missing a header for files

**Comment by Mitchell139** [comment]
- Form saving automatically regardless of whether the user presses the "save" button
- Missing the "Files" header on the Document screen
![image](https://user-images.githubusercontent.com/50130291/191880065-0cb216e1-1815-4166-94e2-063ce3dc842b.png)

**Comment by Mitchell139** [comment]
Requiring the card type to start with a capital seems a bit over the top and likely to confuse people. 
![image](https://user-images.githubusercontent.com/50130291/192921834-4f2f8931-3b1d-47ca-862f-727deef54fb5.png)


Should these have date pickers or at least an example of the the required input format and stricter input validation 
![image](https://user-images.githubusercontent.com/50130291/192922458-bc358c3f-a98f-4480-935b-b6c072d87f99.png)
