### ISSUE TITLE
As an admin I want to have documented steps to get Xero token so that I can use the token for invoicing

### ISSUE THREAD

**Issue by jinggg-y** [dltxio/idem-mobile#439]
## Context
Documented steps of using postmen to fetch Xero token

## AC
- Given I follow the documented steps
- When I complete them
- Then I will have a fresh Xero token

## Test steps
- Follow documented steps
- Confirm you can acquire a valid Xero token

**Comment by OptimusOpus** [comment]
https://github.com/dltxio/proxy.idem.com.au/pull/71

**Comment by Mitchell139** [comment]
Unable to verify whether token returned is valid. @OptimusOpus advised to wait till https://github.com/dltxio/proxy.idem.com.au/issues/67 is done
