### ISSUE TITLE
Select from device button behaviour incorrect

### ISSUE THREAD

**Issue by jrocca82** [dltxio/idem-mobile#45]
On the documents page, "select from device" button has the same functionality as the "take a photo" button

**Comment by bitcoinbrisbane** [comment]
Not a duplicate button, but the behaviour is incorrect.

**Comment by siarangoh** [comment]
Limit files to accept just pdf and jpg

**Comment by bitcoinbrisbane** [comment]
> Limit files to accept just pdf and jpg

Try to write the acceptance critiera too
