### ISSUE TITLE
As IDEM I want to add an "App Coverage File" to our apple submission so IDEM can be available for customers in Australia 

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#450]
Create an app coverage file to add to our apple submission for review. It should show our geographical location "Australia".

**Comment by pondpiu** [comment]
from
https://grantbrits.medium.com/creating-a-routing-app-coverage-file-77c0d8f7802c
and
https://stackoverflow.com/questions/12570409/routing-app-coverage-file

It seems like we only need to upload app coverage file only if we're providing navigation in the app.
I've yet to find that statement from apple website though

**Comment by pondpiu** [comment]
https://help.apple.com/app-store-connect/#/dev4ba662442
