### ISSUE TITLE
As IDEM I want to add Screen shots of the IDEM's metadata to the apple developer review so the apple testers know what the app looks like 

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#452]
Add new updated screens shots of the app for the I-Phone 
Add new updated screen shots of the app for I-Pad view

**Comment by C00p3rb123** [comment]
Please remove and update these screens (except for the pgp screen - just remove that)
![image](https://user-images.githubusercontent.com/48899363/189293399-cc1f4347-e484-44fa-b2da-92079affdff7.png)
![image](https://user-images.githubusercontent.com/48899363/189293561-cea7c597-e850-47e7-942e-6707be6d3d72.png)

**Comment by C00p3rb123** [comment]
settings page for all devices and ipad claims pages

**Comment by Mitchell139** [comment]
Extremely minor discrepancies. Close enough for now
