### ISSUE TITLE
Claims should let you attach documents without an image

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#458]
Metadata for a passport has been filled out but does not let you attach it to a claim

![image](https://user-images.githubusercontent.com/91101134/189560337-22ec7a69-e64f-4fd7-bf66-a060166db5b3.png)

![image](https://user-images.githubusercontent.com/91101134/189560100-694a0537-5318-4ce7-8497-a8b86074530c.png)

**Comment by amagon270** [comment]
This required a bit of a redesign of how evidence is attached to claims.  I wasn't sure how we want that whole system to be implemented so this is working but I think needs to be fully discussed before going ahead with it.
