### ISSUE TITLE
As a business I want to add the referral code for GPIB so user that sign up with IDEM are referred 

### ISSUE THREAD

**Issue by TomDodson** [dltxio/idem-mobile#459]
## AC
- Given I want to signup to GPIB
- When I signup to GPIB using IDEM
- Then the GPIB see an increase in user count with the referral code fb2a2883-5648-48ff-8c49-7cd97f031256

## Test steps
- Login to GPIB admin
- Navgivate to the referrals page https://xxx.getpaidinbitcoin.com.au/referral
- Sign up to GPIB with the a new users
- **"Number of Registers"** should have increased by 1 in the Settings section

![image](https://user-images.githubusercontent.com/8411406/189585023-6b334bdd-46b9-405e-aeb1-b1b84aa87584.png)

Testing with GPIB Test environment:
1. using Alex's referral code: 73ac7899-f08d-453a-90d7-41b253ebabb0
2. login to GPIB admin and navigate to https://testadmin.getpaidinbitcoin.com.au/user/73ac7899-f08d-453a-90d7-41b253ebabb0, should be able to see a new referral record.

**Comment by xiangzhe0812** [comment]
@Mitchell139 @C00p3rb123  test GPIB using. 73ac7899-f08d-453a-90d7-41b253ebabb0  this referral code which is my test account

**Comment by Mitchell139** [comment]
Testing blocked by #507

**Comment by C00p3rb123** [comment]
Referrals are working with @xiangzhe0812 referral code however per the test instructions the **"number of registers** can't be accessed because there is no idem referral code. @bitcoinbrisbane do the testing instructions need to be changed?

**Referral through IDEM 26/9/22**
![image](https://user-images.githubusercontent.com/48899363/192180842-6fac9ceb-7ef5-4e3f-85af-07de9c72afd4.png)

**Comment by bitcoinbrisbane** [comment]
> Referrals are working with @xiangzhe0812 referral code however per the test instructions the **"number of registers"** can't be accessed because there is no idem referral code. @bitcoinbrisbane do the testing instructions need to be changed?
> 
> **Referral through IDEM 26/9/22** ![image](https://user-images.githubusercontent.com/48899363/192180842-6fac9ceb-7ef5-4e3f-85af-07de9c72afd4.png) ![image](https://user-images.githubusercontent.com/48899363/192181660-461269ea-9dc1-4dcf-a11e-b7351a6a844f.png)

@C00p3rb123 which env?

**Comment by C00p3rb123** [comment]
Can't test on prod - currently only set up in testing
![image](https://user-images.githubusercontent.com/48899363/192192613-aff6bffd-3453-417e-a0d9-6f7567cb9c8d.png)
