### ISSUE TITLE
Pgp creation and verification process taking unusually long

### ISSUE THREAD

**Issue by C00p3rb123** [dltxio/idem-mobile#461]
## Test steps to create the bug

PGP processes are taking an awkwardly long time to work since the new page. They use to be instant but now can take a long time and by the looks of it.....time out and fail. 

Tested on my home network and dltx wifi and both process below caused the bug. Hotspot - the bug wasn't present. Once everyone left the office it worked too. Could have something to do with traffic on the network??

**Pgp Creation**
1. Re-install either the latest prod version on test flight or from the app store
2. Fill out name and email claim 
3. Click set up PGP key 
4. Click generate new pgp key - the bug will cause you to wait a few minutes and then return an error message. If this button is working properly it should only take a few seconds for a success message to appear

**Verification Process**
1. Fill out name and email claim
5. Complete Set up PGP process
6. Check emails and click the verification link
7. If it is working properly it should be instantaneous verification otherwise the bug will cause you to wait for 2 min before returning error in the image below
8. Repeat these steps on 2 different networks

<img width="653" alt="image" src="https://user-images.githubusercontent.com/48899363/189592562-70d556f5-be45-4862-bbc8-23b0e9333095.png">

**Comment by bitcoinbrisbane** [comment]
@xiangzhe0812 could the refactor of the end points have broken this?

@C00p3rb123 whats the URL the button is trying to post to?

**Comment by C00p3rb123** [comment]
https://user-images.githubusercontent.com/48899363/189776562-4999e133-6b55-4b7b-bf03-ce5d87bae084.MP4
