### ISSUE TITLE
Email verification page UI change

### ISSUE THREAD

**Issue by jinggg-y** [dltxio/idem-mobile#465]
Distinguish the message to a button
The message "You have been successfully verified, welcome to IDEM" looks like a button. It would be great to change it to plain text.

![image](https://user-images.githubusercontent.com/62837203/189784013-b0a2f5e9-7b5a-4a2e-a6b2-b6bd63b69715.png)

**Comment by bitcoinbrisbane** [comment]
Not required.  See #538
