### ISSUE TITLE
As IDEM, I want the name claim to include middle name, so that Idem can verify via GreenID

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#468]
## Context
GreeenID requires a middle name if a person has one.

## AC
- Given the user is on the Full Name screen
- When they click the middle name field
- Then they are able to add their middle name
- And save their full name  

## Test steps
- Enter your middle name
- And save it

Relates to https://github.com/dltxio/proxy.idem.com.au/issues/59

**Comment by Mitchell139** [comment]
Anytime I try to save a claim (at least Full name and DOB) I get the following error and it doesn't save (spinney boi just keeps spinning)
![img_7882](https://user-images.githubusercontent.com/50130291/190059201-f4bbcd6e-044c-4a3d-a885-6948f0f9b1fc.png)

**Comment by Mitchell139** [comment]
See: https://github.com/dltxio/idem-mobile/issues/303#issuecomment-1246215488

**Comment by JasminFarhi** [comment]
At the moment the validation logic for completing fields for claims is all the same. We need to make another ticket to change this so please disregard that all the fields are mandatory for now.

**Comment by Mitchell139** [comment]
@JasminFarhi @TomDodson Can you sort out creating that new bug before we move this to staging please

**Comment by JasminFarhi** [comment]
Ticket has been made https://github.com/dltxio/idem-mobile/issues/488
