### ISSUE TITLE
As IDEM I want to only include driver license and medicare card as documents so that I can verify the user with greenID

### ISSUE THREAD

**Issue by jinggg-y** [dltxio/idem-mobile#472]
## Context
GreenID only requires a driver's license or a medicare card at the moment. We have the opportunity to expand the documents down the track.

## AC
- When the user is on the document screen
- Then they can only see the document types of driver's license and medicare card

## Test steps
- Open document screen
- Click the "Driver's License"/"Medicare Card" tab
- Entre metadata
- Upload file 
- Successfully save the document
- Be able to toggle the toggle bar on "Full Name", "18+", "Address","DOB" page

**Comment by Mitchell139** [comment]
Shouldn't show other options 
![image](https://user-images.githubusercontent.com/50130291/191878717-ebae9302-dfa1-4305-b69f-7d987a392082.png)


Card Type input immediately removes any characters I type in 
![image](https://user-images.githubusercontent.com/50130291/191878996-3c246830-a5c7-4ba7-a396-299f41a40f91.png)

**Comment by Mitchell139** [comment]
Didn't fix: Card Type input immediately removes any characters I type in
![image](https://user-images.githubusercontent.com/50130291/191897746-500d4f83-9644-4f2a-8fe7-da29055b8c53.png)

**Comment by amagon270** [comment]
input delete Issue fixed in IDEM-438
