### ISSUE TITLE
Change base64 encoded callback URL to plain text on the clients QR code

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#5]
At the moment, the readme has uses Base64 encoding on the claims URL.  Make it more readable and thus more secure by making it plain text.

https://github.com/dltxio/idem-mobile/blob/main/README.md

Current: did://callback=ZGVtby5pZGVtLmNvbS5hdS92ZXJpZnk=?nonce=8b5c66c0-bceb-40b4-b099-d31b127bf7b3&claims=EmailCredential,NameCredential

Expected: did://callback=https://demo.idem.com.au/verify=?nonce=8b5c66c0-bceb-40b4-b099-d31b127bf7b3&claims=EmailCredential,NameCredentia

**Comment by bitcoinbrisbane** [comment]
> Issue is unclear whether this is this just updating the readme or changing the functionality in the app?

App too.  Need to test with a QR code where the query string call back is plain text.

**Comment by Mitchell139** [comment]
Can't test: https://dltxworkspace.slack.com/archives/C01H0NYBBQW/p1654071541354199?thread_ts=1654071297.235279&cid=C01H0NYBBQW
