### ISSUE TITLE
As Lucas, I want to reactor the claims screen to make each screen an individual screen in the code so...

### ISSUE THREAD

**Issue by Mitchell139** [dltxio/idem-mobile#505]
## Context
Currently the claims screen is a dynamic screen but this ticket will make each claim an individual screen

## AC
Given I have the latest update
When I use the claims screens
Then it is all identical in behaviour and functionality to before the refactor

**Comment by Mitchell139** [comment]
@xiangzhe0812

**Comment by bitcoinbrisbane** [comment]
Duplicate #510
