### ISSUE TITLE
No warning modal before resetting data on 3rd parties screen

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#51]
If I click "Reset data" it automatically removes all my information on the profile screen. We should warn users before doing this.
![Image from iOS (101)](https://user-images.githubusercontent.com/83386965/170909457-97d7cc83-0a5e-4187-8eca-77dd5c14abc6.png)

**Comment by bitcoinbrisbane** [comment]
See https://github.com/dltxio/idem-mobile/issues/1

**Comment by bitcoinbrisbane** [comment]
The ticket says the button is on profile page. This is on 3rd partied page https://github.com/dltxio/idem-mobile/issues/42

**Comment by bitcoinbrisbane** [comment]
Not required.
