### ISSUE TITLE
Document details cover-up heading below

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/idem-mobile#53]
On the documents screen 

After adding a couple of documents the details cover the heading for "Attach a file from your device"
![Image from iOS (102)](https://user-images.githubusercontent.com/83386965/170910241-bcc627e7-9062-4052-b869-e1a115a6ef2c.png)

**Comment by jrocca82** [comment]
Fixed on PR-95

**Comment by Mitchell139** [comment]
"Select from device" cut off at the bottom. Guessing that's due to this tickets changes. 
![20220608_152743.jpg](https://user-images.githubusercontent.com/50130291/172538698-21e14e9b-69db-49f4-81f2-852307988a16.jpg)
