### ISSUE TITLE
As IDEM, I want to build on each commit, so that I know my code works

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#60]

**Comment by Mitchell139** [comment]
No testing instructions on how to verify that it builds whenever you commit but based on the husky file (I think that's where it would be right?)  it doesn't look like it would. 
![image](https://user-images.githubusercontent.com/50130291/171362157-f1d56d06-1369-40b3-a67d-4d74ba21b0a5.png)

**Comment by amagon270** [comment]
To test
- create new branch
- commit some change
- on commit the changes should be linted which should look something like this
![image](https://user-images.githubusercontent.com/21031310/171517127-001f472b-ba45-44c3-b668-170015dfeb26.png)
- push the changes
- on push the project should be build which should look something like this
![image](https://user-images.githubusercontent.com/21031310/171517177-94f91430-9c13-472b-9acc-772d4153bb86.png)

**Comment by Mitchell139** [comment]
According to the issue, it should build on commit, not on push.

**Comment by bitcoinbrisbane** [comment]
> According to the issue, it should build on commit, not on push.

Should be push :)

**Comment by Mitchell139** [comment]
Blocked
https://dltxworkspace.slack.com/archives/C01H0NYBBQW/p1654069032488549
https://dltxworkspace.slack.com/archives/C01H0NYBBQW/p1654071541354199?thread_ts=1654071297.235279&cid=C01H0NYBBQW
