### ISSUE TITLE
As an Idem user, I want to add a selfy to my profile, so that I can verify my profile with services that require biometrics

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#7]
Use the camera roll

- Given the profile screen,
- And no selfy has been added before,
- When I take the top left circle,
- Then the im shown my camera roll,
- And I select an image
- And an image is saved to my profile

**Comment by TomDodson** [comment]
@bitcoinbrisbane could the user change their selfie just like they do documents?

**Comment by bitcoinbrisbane** [comment]
> @bitcoinbrisbane could the user change their selfie just like they do documents?

Sounds good.
