### ISSUE TITLE
Can't view submitted document

### ISSUE THREAD

**Issue by Mitchell139** [dltxio/idem-mobile#70]
Submitted document but can't open it to view the details. Might be an Android only problem?
https://user-images.githubusercontent.com/50130291/171365643-ae8e2f67-1139-40fa-9720-c7cc0c3a90e6.mp4

**Comment by Mitchell139** [comment]
Whoops, not sure how or why that moved to review.

**Comment by jrocca82** [comment]
Can cofirm, android problem, hardware only (cannot replicate on emulator). Work around by adding swipe left to view
![Screenshot_20220603-180235_Expo Go](https://user-images.githubusercontent.com/89630724/171814162-e68eaa42-998c-463e-8fbd-d277bd71331c.jpg)
