### ISSUE TITLE
As IDEM, I want more more obs on breaking builds

### ISSUE THREAD

**Issue by xcjlo985** [dltxio/idem-mobile#74]
Implement:
* Build status badge on readme
* Slack notification on builds (success/fail) of main branch

Test steps for slack notification:
1. Commit/push some TS code to this branch that fails a `yarn build`
2. Verify the GitHub CI fails
3. Verify the failure message is posted to slack
4. Revert your code
5. Verify the GitHub CI passes
6. Verify the success message is posted to slack

**Comment by siarangoh** [comment]
I created a webhook in github app on Slack account for DLTX, just need to check when someone push changes to main branch, if any message pop up in slack channel

**Comment by Mitchell139** [comment]
No notifications for build success/failure

**Comment by Mitchell139** [comment]
Slack notifications for build success/failure are currently being sent every time github builds a branch, regardless of what branch it is. Should instead only send slack notification for builds on main branch. 
![image](https://user-images.githubusercontent.com/50130291/173719370-97a10cb1-1075-4d38-9406-f96479d5196d.png)

**Comment by xcjlo985** [comment]
As discussed with Mitchell - this was intention so that the feature could be tested. Without enabling on other branches we'd have to test by breaking the build on main, which is not acceptable. 

Now that the test has passed from a functional perspective, we can lock it down to just main

**Comment by xcjlo985** [comment]
Additional test steps:
1. Verify that main is the only branch that pushes a slack notification after a CI build
2. Verify on main that skipping a build reports as failure
