### ISSUE TITLE
As an new user, I want to see my wallet address on my profile page

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#79]
As a new user,
when I open the app for the first time,
and I am given a mnemonic,
I am also given a wallet address,
which is displayed on my user profile

**Comment by jrocca82** [comment]
needs to be merged to main to test background color due to api call/json set up :)

**Comment by C00p3rb123** [comment]
Requires functionality for importing the seed phrase & private key.

Clarification around front end - "And I click create new"

Address is displayed from the one generated by the mnemonic seed
