### ISSUE TITLE
As an IDEM user, I want to see the details of a 3rd party site, so that I can register with them if I want.

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#86]
On the 3rd parties list, when a user clicks the row they should be taken to a details page.  Those details should be pulled from a JSON object from GitHub, including background colour, logo and blurb.

- Given a user
- And they're on the 3rd parties view,
- When the click "Get Paid In Bitcoin"
- Then they see a details page with the GPIB logo, the correct background colour and a **Sign Up** button
![bPzfuhgEpRmP1AokkS4Sb2](https://user-images.githubusercontent.com/8411406/172087375-ccc65f6b-8ca0-474b-a2b8-387805c6daf1.png)

**Comment by Mitchell139** [comment]
Testing blocked by #35

**Comment by bitcoinbrisbane** [comment]
Needs to have the blurb too

![image](https://user-images.githubusercontent.com/8411406/172533505-cebd3aef-9663-4c87-b784-86c78297df9b.png)

**Comment by jrocca82** [comment]
![Screenshot 2022-06-06 140003](https://user-images.githubusercontent.com/89630724/172535019-d9fc8ec8-0834-43ea-ac83-8aa2e58476bc.jpg)

**Comment by Mitchell139** [comment]
https://dltxworkspace.slack.com/archives/C01H0NYBBQW/p1654736818746159?thread_ts=1654733578.343159&cid=C01H0NYBBQW

**Comment by Mitchell139** [comment]
Sign up button gets pushed off the page if you have a long blurb (logo size may or may not also have an impact) ![Screenshot_20220615-113709_Expo Go.jpg](https://user-images.githubusercontent.com/50130291/173717949-5511ce16-49fc-4596-9067-bc1d5fe00ea3.jpg)
