### ISSUE TITLE
As a curious GPIB user, I want to create an account on GPIB, so that I can use their service  and have my details filled out for me

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#89]
The app can create an account and set a temp password on GPIB.  The JSON object should also specify what claims are required for account creation, and password complexity as a regex

- Given an IDEM user,
- And they have completed their Name Claim
- And email claim,
- When the select 3rd parties
- And click GPIB
- And click register
- Then an account is created with their name and email
- And a temp password of complexity `[AZaz09](3)-[AZaz09](3)-[AZaz09](3)`
- And an alert shows them their temp password

**Comment by C00p3rb123** [comment]
Unable to test as I am being referred to the sign up page

**Comment by Mitchell139** [comment]
Blocked https://dltxworkspace.slack.com/archives/C01H0NYBBQW/p1655440519927049

**Comment by jrocca82** [comment]
Body shape changed, need to fix
