### ISSUE TITLE
As a new PGP user, I want to publish my PGP/GPG public key, so I can verify my email

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#9]
1. Click publish public key button in the screen, call proxy end point to store the public key in database and send verification email to user's email address.
2. Once user click the link from the email then set email verified in the db.
3. Click verify email button, check proxy to see email been verified or not.

Park below for now,

~~GPG/PGP encryption requires a public key server, such as keybase.io, https://pgp.mit.edu/ or https://keys.openpgp.org/.   This ticket pushes the users PGP public key to https://keys.openpgp.org/ server.

- Given I am on the PGP import page
- When I click "Generate new PGP Key"
- Then my public key is automatically sent to https://keys.openpgp.org/ to be verified and I receive a verification email from https://keys.openpgp.org/ 

Depends on #10~~

**Comment by TomDodson** [comment]
Need some designs and more AC.

**Comment by JasminFarhi** [comment]
For testing https://www.attogtech.com/pgp-key-generator/

**Comment by amagon270** [comment]
I got most of the way with the functionality on branch IDEM-9.  I can upload the public key but for some reason it doesn't send the email to be verified.

**Comment by bitcoinbrisbane** [comment]
Cant proceed to the react native lib is changed.

**Comment by C00p3rb123** [comment]
Moved to blocked because of #10

**Comment by C00p3rb123** [comment]
- "Publish PGP Public Key" button still visible.
- Public Key isn't being sent to  https://keys.openpgp.org/
- Therefore, I'm not receiving an email verification.

**Comment by bitcoinbrisbane** [comment]
"Publish PGP Public Key" button if fine.

**Comment by bitcoinbrisbane** [comment]
![image](https://user-images.githubusercontent.com/8411406/180902809-d395675d-ec7a-4099-bf47-89710cea0d11.png)

**Comment by C00p3rb123** [comment]
Not receiving verification email at our proton mail address.

My testing steps:

1. Add email and name claims. (email claim is our proton address _idemtesting.proton.me_)
2. Tap Generate new PGP key
3. Wait for verification email

If there are more/different steps please update the ticket and put back into testing.

**Comment by C00p3rb123** [comment]
- Not receiving verification email  
- Error popped up saying email could not be be verified - this process is not concerned with verifying the email, it is just sending a verification email. The alert should inform the user to check their emails.

**Comment by Mitchell139** [comment]
Publishing PGP key just isn't working at all. Tried generating the pgp key in the app and importing a key from my device. Then even when I clicked "Publish PGP Public Key" I would never receive an email. I then tried manually uploading and verifying my key by going to https://keys.openpgp.org/upload and even then I didn't receive the verification email...

**Comment by C00p3rb123** [comment]
As of today we have found a process that consistently worked

1. Connect to a network outside of Lloyds on phone. If testing locally this needs to be on your computer too. 
2. Open a new browser
3. Generate an email (preferably not using email on deck). Do not use an email that has been used previously, it seems only one verification link is sent per email
4. Download the latest version of the app or clear the data on your current version
5. Add your generated email address as a claim
6. Add your name as a claim
7. Hit Generate new pgp button
8. You should receive the email

Any deviation from these steps tend to result in the email not being sent. Occasionally email addresses will work on Lloyds wifi

**Comment by Mitchell139** [comment]
Imported private key and then clicked "Publish PGP public key" but got an error and didn't receive the verification email. https://user-images.githubusercontent.com/50130291/185303061-c5256edd-8f74-46fe-9bfe-02baf7638820.mp4

**Comment by C00p3rb123** [comment]
A user can skip the verification process if they enter an address has been previously verified. This is a potential security problem as a user could make a claim with an already verified address that isn't theirs and sign up to exchanges. 

https://user-images.githubusercontent.com/48899363/187187097-054ac776-5bd1-4a2a-9197-c810b9be0cb2.MP4

**Comment by xiangzhe0812** [comment]
@C00p3rb123 Had chat with Lucas, should be all good if email previous verified

**Comment by JasminFarhi** [comment]
Remove the cancel from the alert button - from internal showcase
