### ISSUE TITLE
As an unverified GPIB user, I want IDEM to update my account, so that I can verify my GPIB account

### ISSUE THREAD

**Issue by bitcoinbrisbane** [dltxio/idem-mobile#90]
If a user has created an account on GPIB, they can update their details through IDEM.  Relates to https://github.com/dltxio/idem-mobile/issues/89

On the sites.json have another property called "use proxy" as a boolean, and set this to false.  If false call direct.

- Given an IDEM user with a GPIB account
- And they have entered name, email (same as GPIB), and birthday claims,
- When they go to the 3rd parties page,
- And select GPIB,
- And say "Sync Details"
- And they enter their GPIB password and confirm,
- Then GPIB is updated with first name, last name, and year of birth

GPIB swagger
https://testapi.getpaidinbitcoin.com.au/swagger/index.html

**Comment by jrocca82** [comment]
Need to finish connection with GPIB on #89 first

**Comment by jrocca82** [comment]
Mostly done but need new endpoint from GPIB

**Comment by jrocca82** [comment]
NOTE FOR TESTERS: Prompt will only appear on iOS

**Comment by C00p3rb123** [comment]
Blocked by 89

**Comment by jrocca82** [comment]
Body shape changed, need to update
